## Steps in Process:
1. First we need to gather all stocks offering a dividend above $2.00 with an ex_dividend date > today
2. Merge response data into a data frame
3. We then want to asyncrhonousely get all ticker data on these dividends to obtain last close and volume
4. If volume on any of the dividend stocks is < 500,000, remove data from results
5. Get all prior dividends on identified stocks with ex_dividend.lt today
6. Get the prior business data along with candles to compare ex and prior performance
7. Add prior business data for day before ex-dividend and ex-dividend to dataframe
8. Subtract day prior to ex and ex-dividend day close prices to observe directional movement in stock

### Steps 1 and 2: gather all stocks offering a dividend above $2.00 with an ex_dividend date > today and merge to dataframe

In [1]:
import requests 
import pandas as pd
from datetime import date

today = date.today() #set todays date
headers = {'Authorization': 'Bearer 6_I3juoqn42n_W7Tgc6ikNrfdlP8ry29'} #authentication routing for Polygon API

dividend_url = 'https://api.polygon.io/v3/reference/dividends' #polygon api endpoint for dividends
#set payload and sort by cash amount with greater than $2.00
dividend_payload = {
    'ex_dividend_date.gt': today,
    'cash_amount.gt': 2,
    'limit': 1000,
    'sort': 'cash_amount',
    
} 

r = requests.get(dividend_url, headers=headers, params=dividend_payload).json() #get the response object
df = pd.DataFrame(r['results'])
df.sort_values(['ex_dividend_date'], inplace=True)
df = df[['ticker', 'cash_amount', 'dividend_type','declaration_date','ex_dividend_date','record_date','pay_date']]
df = df.round({'last_close': 2, 'cash_amount': 2})
df

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date
1,BKE,2.65,SC,2022-12-06,2023-01-12,2023-01-13,2023-01-27
2,WSO.B,2.45,CD,2023-01-03,2023-01-13,2023-01-17,2023-01-31
3,WSO,2.45,CD,2023-01-03,2023-01-13,2023-01-17,2023-01-31
0,COKE,3.00,SC,2022-12-07,2023-01-26,2023-01-27,2023-02-10
4,AMGN,2.13,CD,2022-12-12,2023-02-14,2023-02-15,2023-03-08

### Step 3: Asyncrhonousely get all ticker data on these dividends to obtain last close and volume

In [2]:
# https://stackoverflow.com/questions/67944791/fastest-way-to-apply-an-async-function-to-pandas-dataframe
import asyncio
import nest_asyncio
import numpy as np
import pandas as pd

nest_asyncio.apply()

async def ticker_data(x):
    '''
        Async definition to retrieve all ticker data for last close and last volume
    '''
    ticker_url = 'https://api.polygon.io/v2/aggs/ticker/{}/prev?adjusted=true'.format(x)
    ticker_data = requests.get(ticker_url, headers=headers).json()
    last_close = ticker_data['results'][0]['c']
    last_volume = ticker_data['results'][0]['v']
    return last_close, last_volume


async def main():
    x = pd.DataFrame(np.arange(len(df)))
    #zip output of async function to new columns in dataframe
    df['last_close'], df['last_volume'] = zip(*await asyncio.gather(*(ticker_data(x) for x in df['ticker'])))

asyncio.run(main())

### Step 4: If volume on any of the dividend stocks is < 500,000, remove data from results

In [3]:
high_volume = df[df['last_volume'].between(500000, 999999999999)] #filter by volume > 500,000
low_volume = df[df['last_volume'].between(0, 500000)]

In [4]:
high_volume

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date,last_close,last_volume
1,BKE,2.65,SC,2022-12-06,2023-01-12,2023-01-13,2023-01-27,47.88,507786.0
4,AMGN,2.13,CD,2022-12-12,2023-02-14,2023-02-15,2023-03-08,275.20,2887810.0

In [5]:
low_volume

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date,last_close,last_volume
2,WSO.B,2.45,CD,2023-01-03,2023-01-13,2023-01-17,2023-01-31,262.32,307.0
3,WSO,2.45,CD,2023-01-03,2023-01-13,2023-01-17,2023-01-31,262.31,226934.0
0,COKE,3.00,SC,2022-12-07,2023-01-26,2023-01-27,2023-02-10,500.00,26204.0

### Step 5: Get all prior dividends on identified stocks with ex_dividend.lt today

In [6]:
# https://towardsdatascience.com/how-to-convert-json-into-a-pandas-dataframe-100b2ae1e0d8
# https://stackoverflow.com/questions/66864805/json-to-pandas-dataframe-with-nested-lists
# https://stackoverflow.com/questions/952914/how-do-i-make-a-flat-list-out-of-a-list-of-lists

#pd.set_option('display.max_rows', None)

#set the payload to dividends offered less than today
payload = {
    'ticker': '',
    'ex_dividend_date.lt': today,
    'limit': 1000,
    'sort': 'ex_dividend_date'
}

prior_dividends = [] #empty list for storing dividend data

async def get_prior_dividends(ticker):
    #Loop through each ticker in the dataframe and return results to caller
    url = 'https://api.polygon.io/v3/reference/dividends'
    payload['ticker'] = ticker
    r = requests.get(url, headers=headers, params=payload).json()
    prior_dividends.append(r['results'])


async def main():
    #loop through and asynchronously process each ticker in the dataframe
    await asyncio.gather(*(get_prior_dividends(ticker) for ticker in high_volume['ticker']))

asyncio.run(main())

flat_list = [item for sublist in prior_dividends for item in sublist] #flatten the items for insertion into dataframe
div_yields = pd.DataFrame.from_dict(flat_list)

In [7]:
div_yields

,cash_amount,currency,declaration_date,dividend_type,ex_dividend_date,frequency,pay_date,record_date,ticker
0,0.35,USD,2022-09-13,CD,2022-10-13,4,2022-10-28,2022-10-14,BKE
1,0.35,USD,2022-07-07,CD,2022-07-14,4,2022-07-29,2022-07-15,BKE
2,0.35,USD,2022-03-22,CD,2022-04-13,4,2022-04-28,2022-04-14,BKE
3,5.65,USD,2021-12-03,SC,2021-12-17,0,2021-12-29,2021-12-20,BKE
4,0.35,USD,2021-12-03,CD,2021-12-17,4,2021-12-29,2021-12-20,BKE
...,...,...,...,...,...,...,...,...,...
131,0.36,USD,2012-07-20,CD,2012-08-14,4,2012-09-07,2012-08-16,AMGN
132,0.36,USD,2012-03-16,CD,2012-05-14,4,2012-06-07,2012-05-16,AMGN
133,0.36,USD,2011-12-16,CD,2012-02-13,4,2012-03-07,2012-02-15,AMGN
134,0.28,USD,2011-10-14,CD,2011-11-15,4,2011-12-08,2011-11-17,AMGN
135,0.28,USD,2011-07-30,CD,2011-08-16,4,2011-09-08,2011-08-18,AMGN

## Now sort the tickers by dividend date and update dataframe

In [8]:
div_yields = div_yields[['ticker','ex_dividend_date','cash_amount','dividend_type','frequency','declaration_date','record_date','pay_date']]
div_yields = div_yields.round({'cash_amount': 2})
div_yields

,ticker,ex_dividend_date,cash_amount,dividend_type,frequency,declaration_date,record_date,pay_date
0,BKE,2022-10-13,0.35,CD,4,2022-09-13,2022-10-14,2022-10-28
1,BKE,2022-07-14,0.35,CD,4,2022-07-07,2022-07-15,2022-07-29
2,BKE,2022-04-13,0.35,CD,4,2022-03-22,2022-04-14,2022-04-28
3,BKE,2021-12-17,5.65,SC,0,2021-12-03,2021-12-20,2021-12-29
4,BKE,2021-12-17,0.35,CD,4,2021-12-03,2021-12-20,2021-12-29
...,...,...,...,...,...,...,...,...
131,AMGN,2012-08-14,0.36,CD,4,2012-07-20,2012-08-16,2012-09-07
132,AMGN,2012-05-14,0.36,CD,4,2012-03-16,2012-05-16,2012-06-07
133,AMGN,2012-02-13,0.36,CD,4,2011-12-16,2012-02-15,2012-03-07
134,AMGN,2011-11-15,0.28,CD,4,2011-10-14,2011-11-17,2011-12-08
135,AMGN,2011-08-16,0.28,CD,4,2011-07-30,2011-08-18,2011-09-08

## Class instance to handle stock market holidays and working days

In [9]:
# https://stackoverflow.com/questions/33094297/create-trading-holiday-calendar-with-pandas/36525605#36525605

import datetime as dt

from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday, nearest_workday, \
    USMartinLutherKingJr, USPresidentsDay, GoodFriday, USMemorialDay, \
    USLaborDay, USThanksgivingDay


class USTradingCalendar(AbstractHolidayCalendar):
    rules = [
        Holiday('NewYearsDay', month=1, day=1, observance=nearest_workday),
        USMartinLutherKingJr,
        USPresidentsDay,
        GoodFriday,
        USMemorialDay,
        Holiday('USIndependenceDay', month=7, day=4, observance=nearest_workday),
        USLaborDay,
        USThanksgivingDay,
        Holiday('Christmas', month=12, day=25, observance=nearest_workday)
    ]


def get_trading_close_holidays(year):
    inst = USTradingCalendar()
    return inst.holidays(dt.datetime(year-1, 12, 31), dt.datetime(year, 12, 31))


print(get_trading_close_holidays(2016))
x = '2016-01-01' 
x in get_trading_close_holidays(2016)
    #    DatetimeIndex(['2016-01-01', '2016-01-18', '2016-02-15', '2016-03-25',
    #                   '2016-05-30', '2016-07-04', '2016-09-05', '2016-11-24',
    #                   '2016-12-26'],
    #                  dtype='datetime64[ns]', freq=None)

DatetimeIndex(['2016-01-01', '2016-01-18', '2016-02-15', '2016-03-25',
               '2016-05-30', '2016-07-04', '2016-09-05', '2016-11-24',
               '2016-12-26'],
              dtype='datetime64[ns]', freq=None)

True

## Step 6: Get the prior business data along with candles for ex and prior comparison

In [10]:
from datetime import datetime

ts = pd.DataFrame(div_yields[['ticker','cash_amount','ex_dividend_date']]) #create new dataframe of ex_dividend_date
ts['cash_amount'] = ts['cash_amount'].round(decimals=2) #round cash amount to nearest second decimal
#convert values to datetime objects for use in lambda function below
ts['ex_dividend_date'] = pd.to_datetime(ts['ex_dividend_date'])


#get the lst business day before the ex-dividend date
ts['prior_business_date'] = pd.DatetimeIndex(ts.ex_dividend_date) - pd.DateOffset(1)
#convert the ticker value to a string
ts['ticker'] = ts['ticker'].astype(str) 
#convert the prior date value back to a string
ts['prior_business_date'] = ts['prior_business_date'].astype(str)
#convert the ex-dividend date value back to a string
ts['ex_dividend_date'] = ts['ex_dividend_date'].astype(str)
#convert the prior business date value back to a string
ts['prior_business_date'] = ts['prior_business_date'].astype(str)

div_yields = pd.merge(div_yields,ts)
div_yields = div_yields[['ticker','prior_business_date', 'ex_dividend_date','cash_amount','dividend_type','frequency','declaration_date','record_date','pay_date']]

In [305]:
#div_yields.dtypes #debugging for code below

In [306]:
#'2022-09-05' in get_trading_close_holidays(int(ts['prior_business_date'][0].split('-')[0])) #debugging to confirm date class working

In [307]:
'''
result = [(x, y, z) for (x, y, z) in zip(div_yields['ticker'], div_yields['prior_business_date'], div_yields['ex_dividend_date'])]
# for i in result:
#     print(type(i[1]))
# result[0]
# for i in result:
#     print(type(i[1]))
    
[list(i) for i in result]
'''
#debugging to confirm output of generator object to list for consumption by asynchronous function below

"\nresult = [(x, y, z) for (x, y, z) in zip(div_yields['ticker'], div_yields['prior_business_date'], div_yields['ex_dividend_date'])]\n# for i in result:\n#     print(type(i[1]))\n# result[0]\n# for i in result:\n#     print(type(i[1]))\n    \n[list(i) for i in result]\n"

## Get Ticker, prior close and ex-dividend close, then obtain bar data for last close
The goal here is to get the candlestick data on the day before the ex-dividend date as well on the ex-dividend date to use as compairson information on performance over time. Ideally, this will be completed asynchronously to provide scale and speed. Once complete, comparisons on movement up or down on the underlying security on the ex-dividend date can be captured and stored for future review, informing trading decisions.

In [14]:
# https://stackoverflow.com/questions/31523302/performance-of-pandas-custom-business-day-offset
from datetime import datetime
from pandas.tseries.offsets import BDay

prior_biz_close = []
xdiv_close = []
to_drop = []

'''
    to_drop likely includes many days where the business day provided falls on a weekend. Need to update to 
    allow for conversion of incorrect days to working days.
'''

async def get_history(data, idx):
    '''
        Receives the ticker, prior business date and ex-dividend date from the caller as a string
        First checks to see if the prior business date (date before Ex-Dividend is a holidy
        If the date is a holiday, subtracts one day from prior business date
        Function then assigns to value x the prior candlestick date for the corrected date
        If the date IS NOT a holiday, the function gets the prior candlestick data based on the prior business date
        Function also returns candlestick data on the ex-dividend date before returning asynchronously to the caller
    '''
    #print(data)
    if data[1] in get_trading_close_holidays(int(data[1].split('-')[0])):
        #set the prior_business date to datetime object
        #deduct 1 day from prior_business_date to get useable data
        data[1] = datetime.strftime(datetime.strptime(data[1],'%Y-%m-%d').date() - BDay(1), '%Y-%m-%d')
        
    url = 'https://api.polygon.io/v2/aggs/ticker/{}/range/1/day/{}/{}?sort=dsc&limit=10'.format(data[0], data[1], data[2])
    r = requests.get(url, headers=headers).json()
    
    if (r['queryCount'] < 2) or (r == None):
        to_drop.append(idx)
        pass
    else:
        #print(type(r))
        prior_biz_close.append(r['results'][0]['c']) #first data set in results is prior date; get only close
        xdiv_close.append(r['results'][1]['c']) #second data set in results is ex-dividend date get only close
        #print(type(x),type(y))

async def main():
    result = [(ticker, prior_business_date, ex_dividend_date) for (ticker, prior_business_date, ex_dividend_date) in zip(div_yields['ticker'], div_yields['prior_business_date'], div_yields['ex_dividend_date'])]
    for i in result:
        await get_history(list(i), result.index(i))
        
asyncio.run(main())

In [308]:
#to_drop #debugging to validate what dates are missing from div_yields history

In [24]:
prior_biz_close

[33.65,
 27.69,
 32.03,
 47.05,
 47.05,
 40.18,
 46.7,
 42.39,
 32.47,
 32.47,
 23.63,
 26.56,
 26.56,
 19.35,
 17.02,
 18.69,
 20.45,
 20.45,
 21.49,
 25.6,
 23.85,
 22.3,
 22.3,
 283.6,
 253.15,
 252.07,
 238.46,
 237.14,
 240.46,
 237.98,
 227,
 219.67,
 206.12,
 169.87,
 188.98,
 190.36,
 195.26,
 172.34,
 175.94]

In [23]:
div_yields

,ticker,prior_business_date,ex_dividend_date,cash_amount,dividend_type,frequency,declaration_date,record_date,pay_date
0,BKE,2022-10-12,2022-10-13,0.35,CD,4,2022-09-13,2022-10-14,2022-10-28
1,BKE,2022-07-13,2022-07-14,0.35,CD,4,2022-07-07,2022-07-15,2022-07-29
2,BKE,2022-04-12,2022-04-13,0.35,CD,4,2022-03-22,2022-04-14,2022-04-28
3,BKE,2021-12-16,2021-12-17,5.65,SC,0,2021-12-03,2021-12-20,2021-12-29
4,BKE,2021-12-16,2021-12-17,0.35,CD,4,2021-12-03,2021-12-20,2021-12-29
5,BKE,2021-10-13,2021-10-14,0.33,CD,4,2021-09-14,2021-10-15,2021-10-29
6,BKE,2021-07-13,2021-07-14,0.33,CD,4,2021-06-08,2021-07-15,2021-07-29
7,BKE,2021-04-13,2021-04-14,0.33,CD,4,2021-03-24,2021-04-15,2021-04-29
8,BKE,2020-12-17,2020-12-18,2.00,SC,0,2020-12-08,2020-12-21,2020-12-29
9,BKE,2020-12-17,2020-12-18,0.30,CD,4,2020-12-08,2020-12-21,2020-12-29
10,BKE,2020-10-13,2020-10-14,0.30,CD,4,2020-09-14,2020-10-15,2020-10-29
11,BKE,2020-01-08,2020-01-09,1.25,SC,0,2019-12-02,2020-01-10,2020-01-24
12,BKE,2020-01-08,2020-01-09,0.30,CD,4,2019-12-02,2020-01-10,2020-01-24
13,BKE,2019-10-09,2019-10-10,0.25,CD,4,2019-09-16,2019-10-11,2019-10-25
14,BKE,2019-07-10,2019-07-11,0.25,CD,4,2019-06-04,2019-07-12,2019-07-26
15,BKE,2019-04-10,2019-04-11,0.25,CD,4,2019-03-26,2019-04-12,2019-04-26
16,BKE,2019-01-09,2019-01-10,0.25,CD,4,2018-12-11,2019-01-11,2019-01-25
17,BKE,2019-01-09,2019-01-10,1.00,SC,0,2018-12-11,2019-01-11,2019-01-25
18,BKE,2018-10-10,2018-10-11,0.25,CD,4,2018-09-18,2018-10-12,2018-10-26
19,BKE,2018-07-11,2018-07-12,0.25,CD,4,2018-06-06,2018-07-13,2018-07-27
20,BKE,2018-04-11,2018-04-12,0.25,CD,4,2018-03-27,2018-04-13,2018-04-27
21,BKE,2018-01-10,2018-01-11,1.75,SC,0,2017-12-05,2018-01-12,2018-01-26
22,BKE,2018-01-10,2018-01-11,0.25,CD,4,2017-12-05,2018-01-12,2018-01-26
27,BKE,2017-01-10,2017-01-11,0.75,SC,0,2016-12-06,2017-01-13,2017-01-25
32,BKE,2016-01-12,2016-01-13,0.25,CD,4,2015-12-08,2016-01-15,2016-01-27
37,BKE,2015-01-12,2015-01-13,0.23,CD,4,2014-12-10,2015-01-15,2015-01-27
42,BKE,2014-01-12,2014-01-13,0.22,CD,4,2013-12-10,2014-01-15,2014-01-27
47,BKE,2012-12-04,2012-12-05,4.50,SC,0,2012-11-05,2012-12-07,2012-12-21
53,BKE,2011-10-11,2011-10-12,0.20,CD,4,2011-09-20,2011-10-14,2011-10-27
63,BKE,2009-10-12,2009-10-13,0.20,CD,4,2009-09-23,2009-10-15,2009-10-27
68,BKE,2008-10-09,2008-10-10,0.20,CD,4,2008-08-29,2008-10-08,NaN
90,AMGN,2022-11-15,2022-11-16,1.94,CD,4,2022-10-28,2022-11-17,2022-12-08
91,AMGN,2022-08-16,2022-08-17,1.94,CD,4,2022-08-03,2022-08-18,2022-09-08
96,AMGN,2021-05-13,2021-05-14,1.76,CD,4,2021-03-03,2021-05-17,2021-06-08
97,AMGN,2021-02-10,2021-02-11,1.76,CD,4,2020-12-16,2021-02-15,2021-03-08
98,AMGN,2020-11-12,2020-11-13,1.60,CD,4,2020-10-21,2020-11-16,2020-12-08
99,AMGN,2020-08-13,2020-08-14,1.60,CD,4,2020-07-23,2020-08-17,2020-09-08
100,AMGN,2020-05-14,2020-05-15,1.60,CD,4,2020-03-04,2020-05-18,2020-06-08
101,AMGN,2020-02-12,2020-02-13,1.60,CD,4,2019-12-11,2020-02-14,2020-03-06
102,AMGN,2019-11-13,2019-11-14,1.45,CD,4,2019-10-22,2019-11-15,2019-12-06
103,AMGN,2019-08-13,2019-08-14,1.45,CD,4,2019-08-02,2019-08-15,2019-09-06
104,AMGN,2019-05-15,2019-05-16,1.45,CD,4,2019-03-07,2019-05-17,2019-06-07
105,AMGN,2019-02-13,2019-02-14,1.45,CD,4,2018-12-07,2019-02-15,2019-03-08
106,AMGN,2018-11-14,2018-11-15,1.32,CD,4,2018-10-23,2018-11-16,2018-12-07
107,AMGN,2018-08-15,2018-08-16,1.32,CD,4,2018-07-31,2018-08-17,2018-09-07
108,AMGN,2018-05-15,2018-05-16,1.32,CD,4,2018-03-07,2018-05-17,2018-06-08
109,AMGN,2018-02-13,2018-02-14,1.32,CD,4,2017-12-12,2018-02-15,2018-03-08

In [16]:
div_yields = div_yields.drop(div_yields.index[[to_drop]]) #drop missing data from the dataframe where bars aren't available
div_yields
'''
    /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py:5055: 
    FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; 
    use `arr[tuple(seq)]` instead of `arr[seq]`. 
    In the future this will be interpreted as an array index, `arr[np.array(seq)]`, 
    which will result either in an error or a different result. result = getitem(key)
'''

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py:5055: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = getitem(key)

'\n    /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py:5055: \n    FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; \n    use `arr[tuple(seq)]` instead of `arr[seq]`. \n    In the future this will be interpreted as an array index, `arr[np.array(seq)]`, \n    which will result either in an error or a different result. result = getitem(key)\n'

## Step 7: Add the prior business close and ex-dividend close data to the dataframe

In [17]:
div_yields['prior_biz_close'] = prior_biz_close
div_yields['xdiv_close'] = xdiv_close

ValueError: Length of values (39) does not match length of index (47)

In [310]:
# div_yields #debugging to validate data in dataframe

## Step 8: Subtract the ex-dividend date from the prior business close to find the delta

In [15]:
div_yields['delta'] =  div_yields['xdiv_close'] - div_yields['prior_biz_close']
div_yields

,ticker,prior_business_date,ex_dividend_date,cash_amount,dividend_type,frequency,declaration_date,record_date,pay_date,prior_biz_close,xdiv_close,delta
0,AMGN,2022-11-15,2022-11-16,1.94,CD,4,2022-10-28,2022-11-17,2022-12-08,283.60,283.77,0.17
1,AMGN,2022-08-16,2022-08-17,1.94,CD,4,2022-08-03,2022-08-18,2022-09-08,253.15,250.58,-2.57
6,AMGN,2021-05-13,2021-05-14,1.76,CD,4,2021-03-03,2021-05-17,2021-06-08,252.07,251.38,-0.69
7,AMGN,2021-02-10,2021-02-11,1.76,CD,4,2020-12-16,2021-02-15,2021-03-08,238.46,235.04,-3.42
8,AMGN,2020-11-12,2020-11-13,1.60,CD,4,2020-10-21,2020-11-16,2020-12-08,237.14,237.36,0.22
9,AMGN,2020-08-13,2020-08-14,1.60,CD,4,2020-07-23,2020-08-17,2020-09-08,240.46,239.71,-0.75
10,AMGN,2020-05-14,2020-05-15,1.60,CD,4,2020-03-04,2020-05-18,2020-06-08,237.98,240.20,2.22
11,AMGN,2020-02-12,2020-02-13,1.60,CD,4,2019-12-11,2020-02-14,2020-03-06,227.00,223.04,-3.96
12,AMGN,2019-11-13,2019-11-14,1.45,CD,4,2019-10-22,2019-11-15,2019-12-06,219.67,218.50,-1.17
13,AMGN,2019-08-13,2019-08-14,1.45,CD,4,2019-08-02,2019-08-15,2019-09-06,206.12,198.87,-7.25
14,AMGN,2019-05-15,2019-05-16,1.45,CD,4,2019-03-07,2019-05-17,2019-06-07,169.87,169.92,0.05
15,AMGN,2019-02-13,2019-02-14,1.45,CD,4,2018-12-07,2019-02-15,2019-03-08,188.98,186.68,-2.30
16,AMGN,2018-11-14,2018-11-15,1.32,CD,4,2018-10-23,2018-11-16,2018-12-07,190.36,192.45,2.09
17,AMGN,2018-08-15,2018-08-16,1.32,CD,4,2018-07-31,2018-08-17,2018-09-07,195.26,196.44,1.18
18,AMGN,2018-05-15,2018-05-16,1.32,CD,4,2018-03-07,2018-05-17,2018-06-08,172.34,173.80,1.46
19,AMGN,2018-02-13,2018-02-14,1.32,CD,4,2017-12-12,2018-02-15,2018-03-08,175.94,179.52,3.58

In [16]:
#https://www.kite.com/blog/python/pandas-groupby-count-value-count/
import numpy as np
v = div_yields.groupby('ticker')

v['delta'].agg(np.mean)
b = pd.DataFrame(v['delta'].agg(np.mean))
b

          delta
ticker
AMGN   -0.69625

In [17]:
g = div_yields.groupby('ticker')['delta']
l = pd.DataFrame(g.agg(
    pos_count=lambda s: s.gt(0).sum(),
    neg_count=lambda s: s.lt(0).sum(),
    net_count=lambda s: s.gt(0).sum() + s.lt(0).sum()).astype(int))
    # open_down=lambda s: pos_count/net_count
t = pd.concat([b,l], axis=1)
t['decrease_liklihood_%'] = (t['neg_count']/t['net_count'])*100 
t['increase_liklihood_%'] = (t['pos_count']/t['net_count'])*100
t.reset_index()

,ticker,delta,pos_count,neg_count,net_count,decrease_liklihood_%,increase_liklihood_%
0,AMGN,-0.69625,8,8,16,50.0,50.0

In [18]:
# https://www.geeksforgeeks.org/how-to-sum-negative-and-positive-values-using-groupby-in-pandas/
def pos(col): 
  return col[col > 0].mean()
  
def neg(col): 
  return col[col < 0].mean()

# print(['Y'].agg([('negative_values', neg),
#                   ('positive_values', pos)
#                   ]))

w = div_yields.groupby(div_yields['ticker'])

s = pd.DataFrame(w['delta'].agg([('average_increase', neg),
                  ('average_decrease', pos)
                  ]))
s = s.fillna(0)
s = abs(s)
s['average_decrease'] = -s['average_decrease']
s = pd.concat([t,s], axis=1)
s = s.round({'delta': 2, 'average_increase': 2, 'average_decrease': 2})
s = s[['pos_count', 'neg_count', 'net_count', 'decrease_liklihood_%', 'average_decrease', 'increase_liklihood_%','average_increase','delta']]
s

,pos_count,neg_count,net_count,decrease_liklihood_%,average_decrease,increase_liklihood_%,average_increase,delta
ticker,,,,,,,,
AMGN,8,8,16,50.0,-1.37,50.0,2.76,-0.7

In [19]:
high_volume

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date,last_close,last_volume
5,AMGN,2.13,CD,2022-12-12,2023-02-14,2023-02-15,2023-03-08,262.64,1622035.0

In [20]:
high_volume = high_volume[['ticker','last_close','last_volume', 'cash_amount', 'dividend_type','ex_dividend_date','record_date','pay_date']]
o = pd.merge(high_volume, s, how="outer", on=["ticker"])
o = o.fillna('-')
o['div%'] = (o['cash_amount']/o['last_close'])*100
o = o.round({'last_close': 2, 'cash_amount': 2, 'div%': 2})
o = o.rename(columns={
    'dividend_type': 'type', 
    'pos_count': '#+', 
    'neg_count': '#-', 
    'net_count': 'total', 
    'decrease_liklihood_%': '↓µ%', 
    'average_decrease': '↓µ$',
    'increase_liklihood_%': '↑µ%',
    'average_increase': '↑µ$',
    'delta': '∆'
})
o.sort_values(['ex_dividend_date'], inplace=True)
o = o[['ticker', 'last_close', 'last_volume', 'cash_amount', 'div%', 'type', 'ex_dividend_date', 'record_date', 'pay_date', '#+', '#-', 'total', '↓µ%', '↓µ$', '↑µ%', '↑µ$', '∆']]
o
# o[o['volume'].between(0, 500000)] #filter by volume > 500,000

,ticker,last_close,last_volume,cash_amount,div%,type,ex_dividend_date,record_date,pay_date,#+,#-,total,↓µ%,↓µ$,↑µ%,↑µ$,∆
0,AMGN,262.64,1622035.0,2.13,0.81,CD,2023-02-14,2023-02-15,2023-03-08,8,8,16,50.0,-1.37,50.0,2.76,-0.7