## Steps in Process:
1. First we need to gather all stocks offering a dividend above $2.00 with an ex_dividend date > today
2. Merge response data into a data frame
3. We then want to asyncrhonousely get all ticker data on these dividends to obtain last close and volume
4. If volume on any of the dividend stocks is < 500,000, remove data from results
5. Get all prior dividends on identified stocks with ex_dividend.lt today
6. Get the prior business data along with candles to compare ex and prior performance
7. Add prior business data for day before ex-dividend and ex-dividend to dataframe
8. Subtract day prior to ex and ex-dividend day close prices to observe directional movement in stock

### Steps 1 and 2: gather all stocks offering a dividend above $2.00 with an ex_dividend date > today and merge to dataframe

In [1]:
import requests 
import pandas as pd
from datetime import date

today = date.today() #set todays date
headers = {'Authorization': 'Bearer 6_I3juoqn42n_W7Tgc6ikNrfdlP8ry29'} #authentication routing for Polygon API

dividend_url = 'https://api.polygon.io/v3/reference/dividends' #polygon api endpoint for dividends
#set payload and sort by cash amount with greater than $2.00
dividend_payload = {
    'ex_dividend_date.gt': today,
    'cash_amount.gt': 1,
    'limit': 1000,
    'sort': 'cash_amount',
    
} 

r = requests.get(dividend_url, headers=headers, params=dividend_payload).json() #get the response object
df = pd.DataFrame(r['results'])
df.sort_values(['ex_dividend_date'], inplace=True)
df = df[['ticker', 'cash_amount', 'dividend_type','declaration_date','ex_dividend_date','record_date','pay_date']]
df = df.round({'last_close': 2, 'cash_amount': 2})
df

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date
0,AVGO,4.60,CD,2023-08-31,2023-09-20,2023-09-21,2023-09-29
1,TKO,3.86,SC,2023-09-13,2023-09-21,2023-09-22,2023-09-29
20,FRT,1.09,CD,2023-08-03,2023-09-21,2023-09-22,2023-10-16
17,PKG,1.25,CD,2023-09-13,2023-09-22,2023-09-25,2023-10-13
22,LOGI,1.06,CD,2023-07-14,2023-09-25,2023-09-26,2023-09-27
14,PM,1.30,CD,2023-09-13,2023-09-26,2023-09-27,2023-10-12
2,ESS,2.31,CD,2023-09-07,2023-09-28,2023-09-29,2023-10-13
21,WPC,1.07,CD,2023-09-14,2023-09-28,2023-09-29,2023-10-16
6,AVB,1.65,CD,2023-09-14,2023-09-28,2023-09-29,2023-10-16
18,ARE,1.24,CD,2023-09-04,2023-09-28,2023-09-29,2023-10-13
16,EGP,1.27,CD,2023-08-25,2023-09-28,2023-09-29,2023-10-13
10,ITW,1.40,CD,2023-08-04,2023-09-28,2023-09-29,2023-10-12
12,DE,1.35,CD,2023-08-30,2023-09-28,2023-09-29,2023-11-08
4,APD,1.75,CD,2023-07-21,2023-09-29,2023-10-02,2023-11-13
23,BNS,1.06,CD,2023-08-29,2023-10-02,2023-10-03,2023-10-27
13,GD,1.32,CD,2023-08-01,2023-10-05,2023-10-06,2023-11-10
9,MAA,1.40,CD,2023-09-12,2023-10-12,2023-10-13,2023-10-31
7,ABBV,1.48,CD,2023-09-08,2023-10-12,2023-10-13,2023-11-15
5,GHC,1.65,CD,2023-09-07,2023-10-17,2023-10-18,2023-11-02
15,CBRL,1.30,CD,2023-09-13,2023-10-19,2023-10-20,2023-11-07
19,LOW,1.10,CD,2023-08-18,2023-10-24,2023-10-25,2023-11-08
11,RY,1.35,CD,2023-08-24,2023-10-25,2023-10-26,2023-11-24
8,BMO,1.47,CD,2023-08-29,2023-10-27,2023-10-30,2023-11-28
3,VRTS,1.90,CD,2023-08-16,2023-10-30,2023-10-31,2023-11-15

### Step 3: Asyncrhonousely get all ticker data on these dividends to obtain last close and volume

In [2]:
# https://stackoverflow.com/questions/67944791/fastest-way-to-apply-an-async-function-to-pandas-dataframe
import asyncio
import nest_asyncio
import numpy as np
import pandas as pd

nest_asyncio.apply()

async def ticker_data(x):
    '''
        Async definition to retrieve all ticker data for last close and last volume
    '''
    ticker_url = 'https://api.polygon.io/v2/aggs/ticker/{}/prev?adjusted=true'.format(x)
    ticker_data = requests.get(ticker_url, headers=headers).json()
    last_close = ticker_data['results'][0]['c']
    last_volume = ticker_data['results'][0]['v']
    return last_close, last_volume


async def main():
    x = pd.DataFrame(np.arange(len(df)))
    #zip output of async function to new columns in dataframe
    df['last_close'], df['last_volume'] = zip(*await asyncio.gather(*(ticker_data(x) for x in df['ticker'])))

asyncio.run(main())

### Step 4: If volume on any of the dividend stocks is < 500,000, remove data from results

In [3]:
high_volume = df[df['last_volume'].between(500000, 999999999999)] #filter by volume > 500,000
low_volume = df[df['last_volume'].between(0, 500000)] #identify all low volume stonks

In [4]:
high_volume

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date,last_close,last_volume
0,AVGO,4.60,CD,2023-08-31,2023-09-20,2023-09-21,2023-09-29,851.68,5018958.0
1,TKO,3.86,SC,2023-09-13,2023-09-21,2023-09-22,2023-09-29,100.11,2453515.0
20,FRT,1.09,CD,2023-08-03,2023-09-21,2023-09-22,2023-10-16,98.82,674064.0
17,PKG,1.25,CD,2023-09-13,2023-09-22,2023-09-25,2023-10-13,149.75,1049844.0
22,LOGI,1.06,CD,2023-07-14,2023-09-25,2023-09-26,2023-09-27,71.53,1013144.0
14,PM,1.30,CD,2023-09-13,2023-09-26,2023-09-27,2023-10-12,95.79,6932697.0
2,ESS,2.31,CD,2023-09-07,2023-09-28,2023-09-29,2023-10-13,225.22,596433.0
21,WPC,1.07,CD,2023-09-14,2023-09-28,2023-09-29,2023-10-16,64.08,1735178.0
6,AVB,1.65,CD,2023-09-14,2023-09-28,2023-09-29,2023-10-16,183.89,1391249.0
18,ARE,1.24,CD,2023-09-04,2023-09-28,2023-09-29,2023-10-13,113.73,1892239.0
16,EGP,1.27,CD,2023-08-25,2023-09-28,2023-09-29,2023-10-13,178.82,560439.0
10,ITW,1.40,CD,2023-08-04,2023-09-28,2023-09-29,2023-10-12,238.31,1541503.0
12,DE,1.35,CD,2023-08-30,2023-09-28,2023-09-29,2023-11-08,412.11,1986245.0
4,APD,1.75,CD,2023-07-21,2023-09-29,2023-10-02,2023-11-13,302.11,1354643.0
23,BNS,1.06,CD,2023-08-29,2023-10-02,2023-10-03,2023-10-27,48.44,1412380.0
13,GD,1.32,CD,2023-08-01,2023-10-05,2023-10-06,2023-11-10,224.05,1829031.0
9,MAA,1.40,CD,2023-09-12,2023-10-12,2023-10-13,2023-10-31,138.00,970359.0
7,ABBV,1.48,CD,2023-09-08,2023-10-12,2023-10-13,2023-11-15,152.12,8868282.0
15,CBRL,1.30,CD,2023-09-13,2023-10-19,2023-10-20,2023-11-07,69.43,1082434.0
19,LOW,1.10,CD,2023-08-18,2023-10-24,2023-10-25,2023-11-08,220.02,9188534.0
11,RY,1.35,CD,2023-08-24,2023-10-25,2023-10-26,2023-11-24,91.51,1317577.0
8,BMO,1.47,CD,2023-08-29,2023-10-27,2023-10-30,2023-11-28,88.56,1149801.0

In [5]:
low_volume

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date,last_close,last_volume
5,GHC,1.65,CD,2023-09-07,2023-10-17,2023-10-18,2023-11-02,585.81,72750.0
3,VRTS,1.90,CD,2023-08-16,2023-10-30,2023-10-31,2023-11-15,206.75,115761.0

### Step 5: Get all prior dividends on identified stocks with ex_dividend.lt today

In [6]:
# https://towardsdatascience.com/how-to-convert-json-into-a-pandas-dataframe-100b2ae1e0d8
# https://stackoverflow.com/questions/66864805/json-to-pandas-dataframe-with-nested-lists
# https://stackoverflow.com/questions/952914/how-do-i-make-a-flat-list-out-of-a-list-of-lists

#pd.set_option('display.max_rows', None)

#set the payload to dividends offered less than today
import datetime
'''
    The polygon API starter package only allows 5 years of historical data.
    In order to prevent invalid API responses for dates > 5 years ago, we need to create a new date object
    that represents the current date less five years and limit responses to that from the API request.
    We create that below with the five_years_ago variable.
'''
four_years_ago = date.today() - datetime.timedelta(days=4*365)
four_years_ago = four_years_ago.strftime('%Y-%m-%d')
# x = div_yields[~(div_yields['ex_dividend_date'] < five_years_ago)]

# x
payload = {
    'ticker': '',
    'ex_dividend_date.lte':today, #set maximum date parameter
    'ex_dividend_date.gt': four_years_ago, #set minimum date parameter
    'limit': 1000,
    'sort': 'ex_dividend_date'
}

prior_dividends = [] #empty list for storing dividend data

async def get_prior_dividends(ticker):
    #Loop through each ticker in the dataframe and return results to caller
    url = 'https://api.polygon.io/v3/reference/dividends'
    payload['ticker'] = ticker
    r = requests.get(url, headers=headers, params=payload).json()
    prior_dividends.append(r['results'])


async def main():
    #loop through and asynchronously process each ticker in the dataframe
    await asyncio.gather(*(get_prior_dividends(ticker) for ticker in high_volume['ticker']))

asyncio.run(main())

flat_list = [item for sublist in prior_dividends for item in sublist] #flatten the items for insertion into dataframe
div_yields = pd.DataFrame.from_dict(flat_list)

## Now sort the tickers by dividend date and update dataframe

In [7]:
# pd.set_option('display.max_rows', None)
div_yields = div_yields[['ticker','ex_dividend_date','cash_amount','dividend_type','frequency','declaration_date','record_date','pay_date']]
div_yields = div_yields.round({'cash_amount': 2})
# div_yields

## Class instance to handle stock market holidays and working days

In [8]:
from USActiveStockTrading import USActiveStockTrading
m = USActiveStockTrading()

## Step 6: Get the prior business data along with candles for ex and prior comparison

In [9]:
from datetime import datetime

ts = pd.DataFrame(div_yields[['ticker','cash_amount','ex_dividend_date']]) #create new dataframe of ex_dividend_date
ts['cash_amount'] = ts['cash_amount'].round(decimals=2) #round cash amount to nearest second decimal
#convert values to datetime objects for use in lambda function below
ts['ex_dividend_date'] = pd.to_datetime(ts['ex_dividend_date'])


#get the lst business day before the ex-dividend date
ts['prior_business_date'] = pd.DatetimeIndex(ts.ex_dividend_date) - pd.DateOffset(1)
#convert the ticker value to a string
ts['ticker'] = ts['ticker'].astype(str) 
#convert the prior date value back to a string
ts['prior_business_date'] = ts['prior_business_date'].astype(str)
#convert the ex-dividend date value back to a string
ts['ex_dividend_date'] = ts['ex_dividend_date'].astype(str)
#convert the prior business date value back to a string
ts['prior_business_date'] = ts['prior_business_date'].astype(str)

div_yields = pd.merge(div_yields,ts)
div_yields = div_yields[['ticker','prior_business_date', 'ex_dividend_date','cash_amount','dividend_type','frequency','declaration_date','record_date','pay_date']]

In [10]:
div_yields

,ticker,prior_business_date,ex_dividend_date,cash_amount,dividend_type,frequency,declaration_date,record_date,pay_date
0,AVGO,2023-06-20,2023-06-21,4.60,CD,4,2023-06-01,2023-06-22,2023-06-30
1,AVGO,2023-03-20,2023-03-21,4.60,CD,4,2023-03-03,2023-03-22,2023-03-31
2,AVGO,2022-12-18,2022-12-19,4.60,CD,4,2022-12-08,2022-12-20,2022-12-30
3,AVGO,2022-09-20,2022-09-21,4.10,CD,4,2022-09-01,2022-09-22,2022-09-30
4,AVGO,2022-06-20,2022-06-21,4.10,CD,4,2022-05-26,2022-06-22,2022-06-30
...,...,...,...,...,...,...,...,...,...
313,BMO,2020-10-29,2020-10-30,1.06,CD,4,2020-08-25,2020-11-02,2020-11-26
314,BMO,2020-08-02,2020-08-03,1.06,CD,4,2020-05-27,2020-08-04,2020-08-26
315,BMO,2020-04-29,2020-04-30,1.06,CD,4,2020-02-25,2020-05-01,2020-05-26
316,BMO,2020-01-30,2020-01-31,1.06,CD,4,2019-12-03,2020-02-03,2020-02-26
317,BMO,2019-10-30,2019-10-31,1.03,CD,4,2019-08-27,2019-11-01,2019-11-26

### Get all of the dates that are not active trading days

In [11]:
#strip date data of dashes for use with USActiveStockTrading
stp = div_yields.applymap(lambda x: x.replace('-', '') if isinstance(x, str) else x)
#get Boolean list of all dates where market is not open
stp['date_valid'] = [m.is_open(i) for i in stp['prior_business_date']]

#https://stackoverflow.com/questions/54453309/get-index-of-series-where-value-is-true
#https://stackoverflow.com/questions/16729574/how-can-i-get-a-value-from-a-cell-of-a-dataframe

#create index list of all false values
vals = [i for i,j in stp['date_valid'].items() if j==False] 
#get all prior_business dates by index
q = stp.iloc[vals]['prior_business_date']
# q #debugging

In [12]:
# q.index

In [13]:
#loop through all dates and get last close
corrected_dates = []
for date in q:
    corrected_dates.append(m.last_close(date))
# corrected_dates

In [14]:
#clean up the ugly data in the div_yields dataframe
def replace_bad_dates(x):
    div_yields.at[x[0], 'prior_business_date'] = x[1]
    
result = zip(q.index, corrected_dates)
for i in list(result):
    replace_bad_dates(i)

In [15]:
# div_yields.iloc[133] #debugging

In [16]:
# res = [*set(div_yields['prior_business_date'])] #remove duplicates in to_drop
# res

## Get Ticker, prior close and ex-dividend close, then obtain bar data for last close
The goal here is to get the candlestick data on the day before the ex-dividend date as well on the ex-dividend date to use as compairson information on performance over time. Ideally, this will be completed asynchronously to provide scale and speed. Once complete, comparisons on movement up or down on the underlying security on the ex-dividend date can be captured and stored for future review, informing trading decisions.

In [17]:
# # https://stackoverflow.com/questions/31523302/performance-of-pandas-custom-business-day-offset
# from datetime import datetime
# from pandas.tseries.offsets import BDay

# prior_biz_close = []
# xdiv_close = []
# to_drop = []
# # missing_dates = []

# '''
#     to_drop likely includes many days where the business day provided falls on a weekend. Need to update to 
#     allow for conversion of incorrect days to working days.
# '''

# async def get_history(data, idx):
#     '''
#         Receives the ticker, prior business date and ex-dividend date from the caller as a string
#         First checks to see if the prior business date (date before Ex-Dividend is a holidy
#         If the date is a holiday, subtracts one day from prior business date
#         Function then assigns to value x the prior candlestick date for the corrected date
#         If the date IS NOT a holiday, the function gets the prior candlestick data based on the prior business date
#         Function also returns candlestick data on the ex-dividend date before returning asynchronously to the caller
#     '''
#     #print(data)
#     # if data[1] in get_trading_close_holidays(int(data[1].split('-')[0])):
#     #     #set the prior_business date to datetime object
#     #     #deduct 1 day from prior_business_date to get useable data
#     #     data[1] = datetime.strftime(datetime.strptime(data[1],'%Y-%m-%d').date() - BDay(1), '%Y-%m-%d')
# # try:   
#     url = 'https://api.polygon.io/v2/aggs/ticker/{}/range/1/day/{}/{}?sort=dsc&limit=10'.format(data[0], data[1], data[2])
#     r = requests.get(url, headers=headers).json()

#     if (r['queryCount'] < 2) or (r == None):
#         to_drop.append(idx)
#         prior_biz_close.append(0.00) #first data set in results is prior date; get only close
#         xdiv_close.append(0.00) #second data set in results is ex-dividend date get only close

#         # print(f'{data[0]}: {data[1]} | {data[2]}')
#         # missing_dates.append((data[1], data[2]))
#         pass
#     else:
#         #print(type(r))
#         prior_biz_close.append(r['results'][0]['c']) #first data set in results is prior date; get only close
#         xdiv_close.append(r['results'][1]['c']) #second data set in results is ex-dividend date get only close
#         # print(data[1], r['results'][0]['c'], r['results'][1]['c'])
# # except:
# #     print('An error occurred during processing, please try again.')

# async def main():
#     result = [(ticker, prior_business_date, ex_dividend_date) for (ticker, prior_business_date, ex_dividend_date) in zip(div_yields['ticker'], div_yields['prior_business_date'], div_yields['ex_dividend_date'])]
#     # await asyncio.gather(*(get_history(list(i), result.index(i))) for i in result))
#     for i in result:
#         await get_history(list(i), result.index(i))
        
# asyncio.run(main())

In [18]:
import asyncio
import aiohttp
from datetime import datetime

import requests

prior_biz_close = []
xdiv_close = []
to_drop = []

async def get_history_async(data, idx, session):
    url = 'https://api.polygon.io/v2/aggs/ticker/{}/range/1/day/{}/{}?sort=dsc&limit=10'.format(data[0], data[1], data[2])
    async with session.get(url, headers=headers, verify_ssl=False) as resp:
        r = await resp.json()
        print(idx)
        print(data)
        print(r)
        try:
            if (r['queryCount'] < 2) or (r == None) or (r['status'] =='NOT_AUTHORIZED'):
                to_drop.append(idx)
                prior_biz_close.append(0.00) #first data set in results is prior date; get only close
                xdiv_close.append(0.00) #second data set in results is ex-dividend date get only close
                pass
            else:
                prior_biz_close.append(r['results'][0]['c']) #first data set in results is prior date; get only close
                xdiv_close.append(r['results'][1]['c']) #second data set in results is ex-dividend date get only close
        except KeyError:
            pass
            

async def main():
    result = [(ticker, prior_business_date, ex_dividend_date) for (ticker, prior_business_date, ex_dividend_date) in
              zip(div_yields['ticker'], div_yields['prior_business_date'], div_yields['ex_dividend_date'])]

    # asynchronous
    # print(f"{datetime.utcnow()} async start")
    session = aiohttp.ClientSession(trust_env=True)
    tasks = []
    for i in result:
        tasks.append(get_history_async(list(i), result.index(i), session))
    await asyncio.gather(*tasks)
    await session.close()
    # print(f"{datetime.utcnow()} async end")

asyncio.run(main())

40
['PKG', '2021-06-11', '2021-06-14']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1265243.0, 'vw': 143.6046, 'o': 143.28, 'c': 143.85, 'h': 144.07, 'l': 142.48, 't': 1623384000000, 'n': 14580}, {'v': 864764, 'vw': 139.6103, 'o': 142.97, 'c': 138.86, 'h': 143.255, 'l': 138.44, 't': 1623643200000, 'n': 12858}], 'status': 'OK', 'request_id': 'e135e7575ae3acb1dda6d1a117cb2fa1', 'count': 2}
34
['PKG', '2022-12-15', '2022-12-16']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 709586, 'vw': 132.7962, 'o': 132.17, 'c': 132.88, 'h': 133.76, 'l': 131.24, 't': 1671080400000, 'n': 16456}, {'v': 1097037.0, 'vw': 130.4309, 'o': 131.14, 'c': 130.58, 'h': 131.35, 'l': 129.09, 't': 1671166800000, 'n': 19184}], 'status': 'OK', 'request_id': 'b14883363f1ae8ba955d5be71685f6ef', 'count': 2}
60
['PM', '2020-12-21', '2020-12-22']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 7776591.0, 'vw': 84.0275, 'o': 84.77, 'c': 84.17, 'h': 84.77, 'l': 83.06, 't': 1608526800000, 'n': 47260}, {'v': 5193887.0, 'vw': 82.2312, 'o': 82.67, 'c': 82.19, 'h': 82.74, 'l': 81.27, 't': 1608613200000, 'n': 38522}], 'status': 'OK', 'request_id': 'ad006b33a551269365a14edda9875d19', 'count': 2}
61
['PM', '2020-09-22', '2020-09-23']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4996208.0, 'vw': 77.5595, 'o': 78.05, 'c': 77.01, 'h': 78.79, 'l': 76.88, 't': 1600747200000, 'n': 40066}, {'v': 5164458.0, 'vw': 76.1593, 'o': 76.54, 'c': 75.5, 'h': 77.35, 'l': 75.285, 't': 1600833600000, 'n': 41170}], 'status': 'OK', 'request_id': '88cb61a1806503f96d051781b238b60e', 'count': 2}
16
['FRT', '2023-06-20', '2023-06-21']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 604413, 'vw': 94.4707, 'o': 95.69, 'c': 94.25, 'h': 95.83, 'l': 93.27, 't': 1687233600000, 'n': 11441}, {'v': 411580, 'vw': 92.3684, 'o': 92.8, 'c': 92.37, 'h': 93.025, 'l': 91.75, 't': 1687320000000, 'n': 8851}], 'status': 'OK', 'request_id': '9a4a6216b491050663dd5ee65b0d06ec', 'count': 2}
3
['AVGO', '2022-09-20', '2022-09-21']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1713164.0, 'vw': 493.3541, 'o': 496, 'c': 493.06, 'h': 498.83, 'l': 489.72, 't': 1663646400000, 'n': 58409}, {'v': 2066913.0, 'vw': 488.6735, 'o': 490.99, 'c': 482.14, 'h': 499.88, 'l': 481.77, 't': 1663732800000, 'n': 57611}], 'status': 'OK', 'request_id': '6defd4dcc06019bbff21b5c2cb55be7f', 'count': 2}
17
['FRT', '2023-03-09', '2023-03-10']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 449081, 'vw': 103.3026, 'o': 104.92, 'c': 102.41, 'h': 105.2835, 'l': 102.23, 't': 1678338000000, 'n': 11948}, {'v': 792767, 'vw': 97.6038, 'o': 101.18, 'c': 96.5, 'h': 101.43, 'l': 96.18, 't': 1678424400000, 'n': 18936}], 'status': 'OK', 'request_id': '1a1d82ef9cfaed67095a614a5480fcae', 'count': 2}
6
['AVGO', '2021-12-20', '2021-12-21']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3277047.0, 'vw': 641.2021, 'o': 626.3, 'c': 645.03, 'h': 646.09, 'l': 625.09, 't': 1639976400000, 'n': 88181}, {'v': 3653389.0, 'vw': 641.7526, 'o': 648.1, 'c': 646.24, 'h': 649.47, 'l': 633.3, 't': 1640062800000, 'n': 78251}], 'status': 'OK', 'request_id': 'ba8d72d59b4717e80fe66f0d5df5f266', 'count': 2}
4
['AVGO', '2022-06-20', '2022-06-21']
{'ticker': 'AVGO', 'queryCount': 1, 'resultsCount': 1, 'adjusted': True, 'results': [{'v': 2190065.0, 'vw': 504.7047, 'o': 504.08, 'c': 503.77, 'h': 510.91, 'l': 502.89, 't': 1655784000000, 'n': 53097}], 'status': 'OK', 'request_id': '07317f2616853978dea7c5c4d5cc3c34', 'count': 1}
67
['ESS', '2023-03-29', '2023-03-30']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 434951, 'vw': 203.4208, 'o': 202.37, 'c': 204.31, 'h': 204.32, 'l': 201.665, 't': 1680062400000, 'n': 10706}, {'v': 373985, 'vw': 204.0618, 'o': 204.75, 'c': 204.18, 'h': 205.47, 'l': 202.83, 't': 1680148800000, 'n': 10437}], 'status': 'OK', 'request_id': '406cdb51a8b77d645843a8cd36d64d94', 'count': 2}
32
['PKG', '2023-06-13', '2023-06-14']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 843862, 'vw': 132.5416, 'o': 131.58, 'c': 131.96, 'h': 134.1699, 'l': 131.38, 't': 1686628800000, 'n': 16186}, {'v': 610280, 'vw': 131.8856, 'o': 131.76, 'c': 131.36, 'h': 133.66, 'l': 130.86, 't': 1686715200000, 'n': 14755}], 'status': 'OK', 'request_id': '37594faa073136c03c13c3b9833b8e6b', 'count': 2}
14
['AVGO', '2019-12-19', '2019-12-20']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3179904.0, 'vw': 325.3392, 'o': 329.21, 'c': 324.1, 'h': 329.255, 'l': 323.71, 't': 1576731600000, 'n': 31197}, {'v': 5054233.0, 'vw': 319.1214, 'o': 322.47, 'c': 319, 'h': 322.47, 'l': 316.91, 't': 1576818000000, 'n': 42308}], 'status': 'OK', 'request_id': '0cb618ecd7177e8d8cc20b73b9654bef', 'count': 2}
0
['AVGO', '2023-06-20', '2023-06-21']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2753723.0, 'vw': 869.4116, 'o': 862.66, 'c': 868.03, 'h': 877.07, 'l': 861.0102, 't': 1687233600000, 'n': 83886}, {'v': 2322881.0, 'vw': 851.8049, 'o': 860, 'c': 847.66, 'h': 866, 'l': 844.6, 't': 1687320000000, 'n': 63420}], 'status': 'OK', 'request_id': '61a498c62ca5882099470a141252ef16', 'count': 2}
45
['PKG', '2020-03-11', '2020-03-12']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1225765.0, 'vw': 85.4135, 'o': 87.89, 'c': 85.37, 'h': 88.05, 'l': 83.61, 't': 1583899200000, 'n': 15775}, {'v': 1324488.0, 'vw': 76.2949, 'o': 79.11, 'c': 77.42, 'h': 79.72, 'l': 71.05, 't': 1583985600000, 'n': 17152}], 'status': 'OK', 'request_id': 'a85e94d8ce2b0b59af7453e1ce081171', 'count': 2}
68
['ESS', '2022-12-29', '2022-12-30']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 407549, 'vw': 213.6922, 'o': 210.795, 'c': 214.27, 'h': 214.94, 'l': 210, 't': 1672290000000, 'n': 14969}, {'v': 410860, 'vw': 211.5063, 'o': 211.1, 'c': 211.92, 'h': 212.509, 'l': 209.37, 't': 1672376400000, 'n': 14200}], 'status': 'OK', 'request_id': 'd867d9f60b16fb5bf4bebbdaa84b3bc0', 'count': 2}
22
['FRT', '2021-12-30', '2021-12-31']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 358449, 'vw': 137.4244, 'o': 135.99, 'c': 137.12, 'h': 138.4, 'l': 135.5001, 't': 1640840400000, 'n': 8052}, {'v': 467522, 'vw': 136.6568, 'o': 136.26, 'c': 136.32, 'h': 137.8, 'l': 135.98, 't': 1640926800000, 'n': 8046}], 'status': 'OK', 'request_id': '0d1a4ee76de5f4363f6ae5d7dfb3e201', 'count': 2}
1
['AVGO', '2023-03-20', '2023-03-21']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2585730.0, 'vw': 641.246, 'o': 632.74, 'c': 643.71, 'h': 644.74, 'l': 631.595, 't': 1679284800000, 'n': 58719}, {'v': 2500011.0, 'vw': 638.0668, 'o': 643.09, 'c': 636.75, 'h': 646.59, 'l': 634.33, 't': 1679371200000, 'n': 63618}], 'status': 'OK', 'request_id': 'd17d6574dab69471fa60767ad1a21848', 'count': 2}
25
['FRT', '2021-03-12', '2021-03-15']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 638210, 'vw': 109.8148, 'o': 109.05, 'c': 110.37, 'h': 110.61, 'l': 108.42, 't': 1615525200000, 'n': 8987}, {'v': 528058, 'vw': 109.5876, 'o': 109.38, 'c': 109.6, 'h': 110.66, 'l': 107.7, 't': 1615780800000, 'n': 9081}], 'status': 'OK', 'request_id': '3dd17407b5815a67291f286fec5e849f', 'count': 2}
7
['AVGO', '2021-09-20', '2021-09-21']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3010547.0, 'vw': 494.8009, 'o': 499, 'c': 494.82, 'h': 503, 'l': 488.44, 't': 1632110400000, 'n': 69869}, {'v': 1693622.0, 'vw': 491.404, 'o': 493.49, 'c': 490.99, 'h': 493.75, 'l': 487, 't': 1632196800000, 'n': 42142}], 'status': 'OK', 'request_id': '9df8bdbfac2fdc419b12f7b3146ea71a', 'count': 2}
57
['PM', '2021-09-27', '2021-09-28']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4414898.0, 'vw': 102.4847, 'o': 101.62, 'c': 102.51, 'h': 103.04, 'l': 101.62, 't': 1632715200000, 'n': 35557}, {'v': 6281714.0, 'vw': 98.8128, 'o': 101.3, 'c': 98.42, 'h': 101.3, 'l': 98.121, 't': 1632801600000, 'n': 48968}], 'status': 'OK', 'request_id': '3ccf4896795cd54ddfbfbc05ec7be75c', 'count': 2}
29
['FRT', '2020-03-12', '2020-03-13']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1214818.0, 'vw': 106.2778, 'o': 106.76, 'c': 104.37, 'h': 110.15, 'l': 104.29, 't': 1583985600000, 'n': 23830}, {'v': 1441350.0, 'vw': 103.5858, 'o': 107.5, 'c': 105.7, 'h': 108.91, 'l': 100.135, 't': 1584072000000, 'n': 23431}], 'status': 'OK', 'request_id': '155900e41ebb441bd438cb753cbf506d', 'count': 2}
5
['AVGO', '2022-03-18', '2022-03-21']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4153788.0, 'vw': 608.3589, 'o': 603.97, 'c': 610.41, 'h': 613.21, 'l': 595.99, 't': 1647576000000, 'n': 63182}, {'v': 2578930.0, 'vw': 597.829, 'o': 605.6, 'c': 601.29, 'h': 605.6, 'l': 588.86, 't': 1647835200000, 'n': 61378}], 'status': 'OK', 'request_id': '820e8423cac5fb91bf57382697d0a1ec', 'count': 2}
52
['PM', '2022-12-20', '2022-12-21']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4261446.0, 'vw': 100.9426, 'o': 100.79, 'c': 100.92, 'h': 101.39, 'l': 100.245, 't': 1671512400000, 'n': 36794}, {'v': 5615888.0, 'vw': 100.3131, 'o': 99.9, 'c': 100.52, 'h': 100.595, 'l': 99.69, 't': 1671598800000, 'n': 48176}], 'status': 'OK', 'request_id': 'eca99bda8a14fe3ee12e91361763a630', 'count': 2}
37
['PKG', '2022-03-11', '2022-03-14']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 578362, 'vw': 149.6812, 'o': 150.03, 'c': 149.75, 'h': 150.93, 'l': 148.79, 't': 1646974800000, 'n': 13657}, {'v': 746710, 'vw': 150.7707, 'o': 150.49, 'c': 150.93, 'h': 152.1, 'l': 149.57, 't': 1647230400000, 'n': 14938}], 'status': 'OK', 'request_id': '3a822e36549000aa2b4681f7d8ec2bc7', 'count': 2}
59
['PM', '2021-03-18', '2021-03-19']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 10727533.0, 'vw': 90.3097, 'o': 89, 'c': 90.56, 'h': 91.25, 'l': 88.845, 't': 1616040000000, 'n': 70025}, {'v': 11030648.0, 'vw': 89.341, 'o': 89.14, 'c': 89.25, 'h': 90.015, 'l': 88.57, 't': 1616126400000, 'n': 60704}], 'status': 'OK', 'request_id': 'e89887a3e9ebb45f689d8d1dd90add54', 'count': 2}
44
['PKG', '2020-06-11', '2020-06-12']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 700871, 'vw': 99.5238, 'o': 102.62, 'c': 98.13, 'h': 103.38, 'l': 98.04, 't': 1591848000000, 'n': 11764}, {'v': 589957, 'vw': 98.6351, 'o': 100.7, 'c': 98.92, 'h': 101.57, 'l': 96.23, 't': 1591934400000, 'n': 11957}], 'status': 'OK', 'request_id': '0fe890b630543357584a547039781e4a', 'count': 2}
13
['AVGO', '2020-03-19', '2020-03-20']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 7435821.0, 'vw': 190.7093, 'o': 167.64, 'c': 194.45, 'h': 207.47, 'l': 165, 't': 1584590400000, 'n': 101815}, {'v': 7404367.0, 'vw': 196.9648, 'o': 202, 'c': 192.22, 'h': 208.68, 'l': 187.91, 't': 1584676800000, 'n': 80282}], 'status': 'OK', 'request_id': '7f1bdc877ae9d49a0c16be671b39d070', 'count': 2}
70
['ESS', '2022-06-28', '2022-06-29']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 413409, 'vw': 266.0504, 'o': 266.86, 'c': 264.02, 'h': 270.55, 'l': 263.92, 't': 1656388800000, 'n': 12456}, {'v': 309923, 'vw': 261.9897, 'o': 261.43, 'c': 262.35, 'h': 262.92, 'l': 259.74, 't': 1656475200000, 'n': 9686}], 'status': 'OK', 'request_id': '1a13a77161cf9f6f188efc6d0e27f8c0', 'count': 2}
56
['PM', '2021-12-21', '2021-12-22']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4583522.0, 'vw': 93.239, 'o': 93.51, 'c': 93.04, 'h': 93.78, 'l': 92.88, 't': 1640062800000, 'n': 36916}, {'v': 4877602.0, 'vw': 92.6478, 'o': 91.61, 'c': 92.91, 'h': 92.95, 'l': 91.4163, 't': 1640149200000, 'n': 29695}], 'status': 'OK', 'request_id': '1df08400c9150ebc86ecb586c44bb193', 'count': 2}
33
['PKG', '2023-03-13', '2023-03-14']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 836336, 'vw': 131.3254, 'o': 130.94, 'c': 130.69, 'h': 133.51, 'l': 129.57, 't': 1678680000000, 'n': 18880}, {'v': 788194, 'vw': 131.1587, 'o': 131.43, 'c': 131.35, 'h': 132.42, 'l': 129.74, 't': 1678766400000, 'n': 17046}], 'status': 'OK', 'request_id': '9f47849a0d045468b1c285f43f1bf8d0', 'count': 2}
69
['ESS', '2022-09-28', '2022-09-29']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 746174, 'vw': 244.5925, 'o': 240.86, 'c': 244.7, 'h': 246.22, 'l': 238.17, 't': 1664337600000, 'n': 14047}, {'v': 494543, 'vw': 239.0578, 'o': 240.3, 'c': 238.66, 'h': 241.72, 'l': 236.01, 't': 1664424000000, 'n': 15237}], 'status': 'OK', 'request_id': '78257dacfe8824feb39ce6bc9c5490fa', 'count': 2}
36
['PKG', '2022-06-13', '2022-06-14']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 696621, 'vw': 144.8286, 'o': 148.67, 'c': 143.67, 'h': 149.015, 'l': 142.96, 't': 1655092800000, 'n': 16526}, {'v': 956717, 'vw': 146.3107, 'o': 142.39, 'c': 147.23, 'h': 147.51, 'l': 142.21, 't': 1655179200000, 'n': 23332}], 'status': 'OK', 'request_id': '7f662783ab2a779a285f1234750f9a85', 'count': 2}
53
['PM', '2022-09-26', '2022-09-27']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4482372.0, 'vw': 90.7842, 'o': 91.41, 'c': 90.17, 'h': 92.36, 'l': 90.0499, 't': 1664164800000, 'n': 50792}, {'v': 7067769.0, 'vw': 87.5709, 'o': 89.48, 'c': 87.02, 'h': 90.13, 'l': 86.83, 't': 1664251200000, 'n': 75212}], 'status': 'OK', 'request_id': 'cfb0ff9c4b51088dc11901fb1676a218', 'count': 2}
47
['LOGI', '2022-09-23', '2022-09-26']
{'ticker': 'LOGI', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 773670, 'vw': 45.7892, 'o': 45.64, 'c': 46.09, 'h': 46.16, 'l': 45.41, 't': 1663905600000, 'n': 11751}, {'v': 669511, 'vw': 45.0075, 'o': 44.9, 'c': 44.56, 'h': 45.72, 'l': 44.51, 't': 1664164800000, 'n': 9307}], 'status': 'OK', 'request_id': 'a89437dbd9bd058d732834f216972290', 'count': 2}
15
['AVGO', '2019-09-19', '2019-09-20']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1977918.0, 'vw': 290.1109, 'o': 288.5, 'c': 290.64, 'h': 291.945, 'l': 287.23, 't': 1568865600000, 'n': 26278}, {'v': 3689318.0, 'vw': 285.0677, 'o': 287.67, 'c': 284.26, 'h': 288.4, 'l': 281.82, 't': 1568952000000, 'n': 31996}], 'status': 'OK', 'request_id': '8d23ac9988a38a6f99557a5240e0ae4e', 'count': 2}
78
['ESS', '2020-06-26', '2020-06-29']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 654099, 'vw': 225.4984, 'o': 228.01, 'c': 224.79, 'h': 229.91, 'l': 224, 't': 1593144000000, 'n': 9654}, {'v': 359095, 'vw': 225.3101, 'o': 224.44, 'c': 226.43, 'h': 226.51, 'l': 221.985, 't': 1593403200000, 'n': 10713}], 'status': 'OK', 'request_id': 'fdb38c1284e4027c6bb685234872101e', 'count': 2}
2
['AVGO', '2022-12-16', '2022-12-19']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4954898.0, 'vw': 555.4328, 'o': 557.45, 'c': 555.91, 'h': 559.8, 'l': 550.87, 't': 1671166800000, 'n': 81028}, {'v': 2509318.0, 'vw': 549.0082, 'o': 554.02, 'c': 549.63, 'h': 556.48, 'l': 545.72, 't': 1671426000000, 'n': 60568}], 'status': 'OK', 'request_id': '5bb2d5336f476e9e7fbef79fe1c7f182', 'count': 2}
21
['FRT', '2022-03-14', '2022-03-15']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 464311, 'vw': 117.0238, 'o': 119, 'c': 116.34, 'h': 119.89, 'l': 115.86, 't': 1647230400000, 'n': 10012}, {'v': 566716, 'vw': 116.2478, 'o': 116.16, 'c': 116.64, 'h': 117.35, 'l': 115.24, 't': 1647316800000, 'n': 12827}], 'status': 'OK', 'request_id': '169eb91d5f7b7e996b27dd4d4ee7f554', 'count': 2}
35
['PKG', '2022-09-29', '2022-09-30']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 877818, 'vw': 113.6286, 'o': 113.8, 'c': 114.22, 'h': 114.59, 'l': 111.98, 't': 1664424000000, 'n': 17128}, {'v': 1133420.0, 'vw': 113.0613, 'o': 113.43, 'c': 112.29, 'h': 115.355, 'l': 111.95, 't': 1664510400000, 'n': 17536}], 'status': 'OK', 'request_id': '482684ea06661e57be2588a8925eed9b', 'count': 2}
62
['PM', '2020-06-18', '2020-06-19']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3856176.0, 'vw': 74.3513, 'o': 73.5, 'c': 74.6, 'h': 74.78, 'l': 73.36, 't': 1592452800000, 'n': 29396}, {'v': 10206670.0, 'vw': 72.9997, 'o': 73.91, 'c': 72.2, 'h': 74.34, 'l': 72.12, 't': 1592539200000, 'n': 47843}], 'status': 'OK', 'request_id': 'dd531d07fcf66a469220eabc86e908cc', 'count': 2}
20
['FRT', '2022-06-20', '2022-06-21']
{'ticker': 'FRT', 'queryCount': 1, 'resultsCount': 1, 'adjusted': True, 'results': [{'v': 528015, 'vw': 95.4528, 'o': 95.87, 'c': 94.76, 'h': 96.64, 'l': 94.49, 't': 1655784000000, 'n': 12625}], 'status': 'OK', 'request_id': 'a0b1dc2cf0be2beccaa2f1b989f0023a', 'count': 1}
43
['PKG', '2020-09-11', '2020-09-14']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 683359, 'vw': 104.0784, 'o': 103.64, 'c': 104.61, 'h': 105.1, 'l': 103.06, 't': 1599796800000, 'n': 10324}, {'v': 525723, 'vw': 105.8511, 'o': 104.76, 'c': 105.93, 'h': 106.52, 'l': 104.225, 't': 1600056000000, 'n': 8898}], 'status': 'OK', 'request_id': '16472058a75bdcc9f9726cdea296d817', 'count': 2}
54
['PM', '2022-06-29', '2022-06-30']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2805341.0, 'vw': 101.2376, 'o': 101.88, 'c': 100.87, 'h': 102.6799, 'l': 100.61, 't': 1656475200000, 'n': 31001}, {'v': 4591865.0, 'vw': 98.5011, 'o': 98.66, 'c': 98.74, 'h': 99.06, 'l': 97.69, 't': 1656561600000, 'n': 41652}], 'status': 'OK', 'request_id': 'e5b3be5876c4046c79cca0addb9fe936', 'count': 2}
10
['AVGO', '2020-12-17', '2020-12-18']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1715176.0, 'vw': 427.1423, 'o': 426.5, 'c': 426.1, 'h': 430.01, 'l': 424.545, 't': 1608181200000, 'n': 38052}, {'v': 4524332.0, 'vw': 431.6551, 'o': 424.8, 'c': 434.56, 'h': 435.65, 'l': 422, 't': 1608267600000, 'n': 45170}], 'status': 'OK', 'request_id': '83fdb0d6c5a17394d126751c9f7ed5d6', 'count': 2}
66
['ESS', '2023-06-28', '2023-06-29']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 372568, 'vw': 230.5802, 'o': 229.59, 'c': 230.27, 'h': 233.3, 'l': 228.38, 't': 1687924800000, 'n': 10479}, {'v': 316461, 'vw': 231.7233, 'o': 227.32, 'c': 233.07, 'h': 233.14, 'l': 226.3, 't': 1688011200000, 'n': 9035}], 'status': 'OK', 'request_id': '5c3b931a26870c9359c77b83b30a08bb', 'count': 2}
79
['ESS', '2020-03-27', '2020-03-30']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 791568, 'vw': 224.9398, 'o': 212.21, 'c': 228.6, 'h': 234.8, 'l': 209.41, 't': 1585281600000, 'n': 15834}, {'v': 593657, 'vw': 220.0004, 'o': 228.6, 'c': 225.51, 'h': 232.13, 'l': 211.89, 't': 1585540800000, 'n': 12656}], 'status': 'OK', 'request_id': 'e1d9964c35cfe5ff492a235b6f2b5cb6', 'count': 2}
31
['FRT', '2019-09-19', '2019-09-20']

274
['LOW', '2022-07-18', '2022-07-19']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2965993.0, 'vw': 187.0964, 'o': 186.6053, 'c': 185.79, 'h': 189.08, 'l': 185.19, 't': 1658116800000, 'n': 49849}, {'v': 2683876.0, 'vw': 188.1079, 'o': 186.57, 'c': 188.78, 'h': 189.56, 'l': 184.82, 't': 1658203200000, 'n': 43660}], 'status': 'OK', 'request_id': 'a429be20e25380c3dae27e01673f8631', 'count': 2}
276
['LOW', '2022-01-17', '2022-01-18']
{'ticker': 'LOW', 'queryCount': 1, 'resultsCount': 1, 'adjusted': True, 'results': [{'v': 4612577.0, 'vw': 237.4152, 'o': 239.2, 'c': 238.41, 'h': 239.595, 'l': 234.27, 't': 1642482000000, 'n': 67671}], 'status': 'OK', 'request_id': 'dd9eb7f42e94b0b51fc2369aad751086', 'count': 1}
263
['CBRL', '2022-04-13', '2022-04-14']
{'ticker': 'CBRL', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 446424, 'vw': 117.7643, 'o': 115.48, 'c': 118.51, 'h': 118.91, 'l': 114.81, 't': 1649822400000, 'n': 9419}, {'v': 461155, 'vw': 117.8842, 'o': 117.21, 'c': 118.49, 'h': 118.86, 'l': 116.3845, 't': 1649908800000, 'n': 9758}], 'status': 'OK', 'request_id': '5c4d03bd3406b4a01718e3788e9b50c0', 'count': 2}
126
['ARE', '2020-06-26', '2020-06-29']
{'ticker': 'ARE', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 983500, 'vw': 162.9345, 'o': 167.59, 'c': 161.83, 'h': 167.8, 'l': 161.11, 't': 1593144000000, 'n': 11877}, {'v': 522854, 'vw': 161.2486, 'o': 162.21, 'c': 161.63, 'h': 162.21, 'l': 159.176, 't': 1593403200000, 'n': 11898}], 'status': 'OK', 'request_id': 'd46baddef0cc910e35a68ba755336df4', 'count': 2}
278
['LOW', '2021-07-19', '2021-07-20']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 5218099.0, 'vw': 192.1783, 'o': 191.98, 'c': 192.9, 'h': 193.6659, 'l': 190.04, 't': 1626667200000, 'n': 85384}, {'v': 2927956.0, 'vw': 194.002, 'o': 191.68, 'c': 194.11, 'h': 195.41, 'l': 191.17, 't': 1626753600000, 'n': 46824}], 'status': 'OK', 'request_id': '9ec7c0a30e1a3b2e2ef00c7a241144ba', 'count': 2}
267
['CBRL', '2020-08-12', '2020-08-13']
{'ticker': 'CBRL', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 351014, 'vw': 119.3756, 'o': 122.63, 'c': 119.72, 'h': 123.47, 'l': 117.74, 't': 1597204800000, 'n': 6872}, {'v': 185843, 'vw': 119.7569, 'o': 118.8464, 'c': 119.45, 'h': 121.2, 'l': 117.77, 't': 1597291200000, 'n': 4194}], 'status': 'OK', 'request_id': '6ae7e977412156103abe3fdee0627b95', 'count': 2}
275
['LOW', '2022-04-18', '2022-04-19']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3800438.0, 'vw': 198.6028, 'o': 200.62, 'c': 198.52, 'h': 202, 'l': 197.33, 't': 1650254400000, 'n': 74778}, {'v': 3392926.0, 'vw': 202.2365, 'o': 198.17, 'c': 203.04, 'h': 203.51, 'l': 197.7, 't': 1650340800000, 'n': 61274}], 'status': 'OK', 'request_id': 'bc031f7159ed720d906428faa219a8d3', 'count': 2}
283
['LOW', '2020-04-20', '2020-04-21']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 5354466.0, 'vw': 95.9936, 'o': 95.25, 'c': 95.13, 'h': 97.81, 'l': 94.53, 't': 1587355200000, 'n': 43962}, {'v': 5631412.0, 'vw': 92.7588, 'o': 92.09, 'c': 92.62, 'h': 93.7, 'l': 91.49, 't': 1587441600000, 'n': 62055}], 'status': 'OK', 'request_id': '25d33afc8e4dd064d4bebe60593a8f42', 'count': 2}
277
['LOW', '2021-10-18', '2021-10-19']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2785992.0, 'vw': 221.6734, 'o': 218.4, 'c': 221.74, 'h': 222.71, 'l': 218.27, 't': 1634529600000, 'n': 44851}, {'v': 2976253.0, 'vw': 222.8058, 'o': 221.85, 'c': 222.91, 'h': 223.77, 'l': 221.512, 't': 1634616000000, 'n': 46326}], 'status': 'OK', 'request_id': '4f2fb2ad7753f7f38239415e6970d835', 'count': 2}
279
['LOW', '2021-04-19', '2021-04-20']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3892485.0, 'vw': 204.8035, 'o': 206.01, 'c': 204.01, 'h': 207.2946, 'l': 203.49, 't': 1618804800000, 'n': 62047}, {'v': 3057919.0, 'vw': 202.0299, 'o': 203.42, 'c': 202.77, 'h': 204, 'l': 200.43, 't': 1618891200000, 'n': 50034}], 'status': 'OK', 'request_id': '6740f85cf1628eb3049e9e866e17ffb1', 'count': 2}
269
['CBRL', '2019-10-16', '2019-10-17']
{'ticker': 'CBRL', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 367430, 'vw': 155.5737, 'o': 154.98, 'c': 156.07, 'h': 156.19, 'l': 153.67, 't': 1571198400000, 'n': 6761}, {'v': 255738, 'vw': 155.0942, 'o': 155.46, 'c': 154.84, 'h': 155.71, 'l': 154.5, 't': 1571284800000, 'n': 5046}], 'status': 'OK', 'request_id': '3b4abe057142a7df0ed793b1d042e2fc', 'count': 2}
270
['LOW', '2023-07-24', '2023-07-25']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2018962.0, 'vw': 234.3885, 'o': 234.2, 'c': 234, 'h': 235.81, 'l': 233.58, 't': 1690171200000, 'n': 42481}, {'v': 1547780.0, 'vw': 233.5157, 'o': 232.38, 'c': 233.94, 'h': 234.385, 'l': 231.19, 't': 1690257600000, 'n': 36406}], 'status': 'OK', 'request_id': '5cc2ad8369524f08ceefe20fbd008d9e', 'count': 2}
264
['CBRL', '2022-01-12', '2022-01-13']
{'ticker': 'CBRL', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 379376, 'vw': 130.018, 'o': 132.48, 'c': 128.74, 'h': 133.0286, 'l': 128.67, 't': 1641963600000, 'n': 9144}, {'v': 248194, 'vw': 130.8463, 'o': 127.55, 'c': 130.59, 'h': 132.45, 'l': 127.05, 't': 1642050000000, 'n': 8351}], 'status': 'OK', 'request_id': '728cf53b227ef080c5b1dfe3059fd1bd', 'count': 2}
284
['LOW', '2020-01-20', '2020-01-21']
{'ticker': 'LOW', 'queryCount': 1, 'resultsCount': 1, 'adjusted': True, 'results': [{'v': 3541138.0, 'vw': 121.139, 'o': 121.17, 'c': 120.93, 'h': 121.75, 'l': 120.16, 't': 1579582800000, 'n': 31746}], 'status': 'OK', 'request_id': '1d041936127eee5d2e8dfc64b9e38342', 'count': 1}
280
['LOW', '2021-01-18', '2021-01-19']
{'ticker': 'LOW', 'queryCount': 1, 'resultsCount': 1, 'adjusted': True, 'results': [{'v': 4769015.0, 'vw': 171.457, 'o': 172.9, 'c': 170.76, 'h': 173.81, 'l': 170.64, 't': 1611032400000, 'n': 45245}], 'status': 'OK', 'request_id': '38611d6e9bc473c932be3fb3146383cd', 'count': 1}
282
['LOW', '2020-07-20', '2020-07-21']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2808264.0, 'vw': 143.9934, 'o': 143.33, 'c': 144.1, 'h': 144.71, 'l': 142.9, 't': 1595217600000, 'n': 38726}, {'v': 2681051.0, 'vw': 144.9103, 'o': 143.95, 'c': 145, 'h': 145.9199, 'l': 143.51, 't': 1595304000000, 'n': 35694}], 'status': 'OK', 'request_id': '933a850438402da2220adcb33899834b', 'count': 2}
289
['RY', '2022-10-24', '2022-10-25']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2053928.0, 'vw': 90.5459, 'o': 91.12, 'c': 90.81, 'h': 91.23, 'l': 90.09, 't': 1666584000000, 'n': 8730}, {'v': 1920854.0, 'vw': 89.8602, 'o': 89.37, 'c': 91.02, 'h': 91.25, 'l': 89.34, 't': 1666670400000, 'n': 9055}], 'status': 'OK', 'request_id': 'adcf2bd00e663ee3c3ca514a6716d732', 'count': 2}
295
['RY', '2021-04-20', '2021-04-21']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2815674.0, 'vw': 93.2187, 'o': 93.77, 'c': 92.46, 'h': 94.04, 'l': 92.38, 't': 1618891200000, 'n': 15097}, {'v': 2430364.0, 'vw': 92.0028, 'o': 91.5, 'c': 92.9, 'h': 92.92, 'l': 91.14, 't': 1618977600000, 'n': 11606}], 'status': 'OK', 'request_id': '2aa8ee98c313d15d8391ab6b1313efe8', 'count': 2}
298
['RY', '2020-07-23', '2020-07-24']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3105604.0, 'vw': 71.1728, 'o': 71.14, 'c': 70.91, 'h': 71.421, 'l': 70.83, 't': 1595476800000, 'n': 11030}, {'v': 4858310.0, 'vw': 69.7231, 'o': 70.06, 'c': 69.84, 'h': 70.12, 'l': 69.27, 't': 1595563200000, 'n': 9963}], 'status': 'OK', 'request_id': '97cd23a81aba21ea6599399087b93984', 'count': 2}
293
['RY', '2021-10-22', '2021-10-25']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 931575, 'vw': 107.6752, 'o': 107.31, 'c': 107.75, 'h': 108.09, 'l': 107.21, 't': 1634875200000, 'n': 11007}, {'v': 2201344.0, 'vw': 106.3782, 'o': 107.13, 'c': 106.95, 'h': 107.27, 'l': 106.15, 't': 1635134400000, 'n': 11557}], 'status': 'OK', 'request_id': '18ccffabf120667b9449d0ff0feb014a', 'count': 2}
300
['RY', '2020-01-23', '2020-01-24']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1038594.0, 'vw': 81.3693, 'o': 81.01, 'c': 81.73, 'h': 81.73, 'l': 80.81, 't': 1579755600000, 'n': 11076}, {'v': 971724, 'vw': 80.5786, 'o': 80.95, 'c': 80.48, 'h': 81.17, 'l': 80.24, 't': 1579842000000, 'n': 10743}], 'status': 'OK', 'request_id': 'a014f8b85a336a05cb344fa1e20eabc9', 'count': 2}
291
['RY', '2022-04-21', '2022-04-22']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 911012, 'vw': 111.2728, 'o': 111.78, 'c': 110.18, 'h': 112.67, 'l': 110.07, 't': 1650513600000, 'n': 13929}, {'v': 2272783.0, 'vw': 106.2579, 'o': 108.37, 'c': 104.41, 'h': 108.61, 'l': 104.33, 't': 1650600000000, 'n': 15643}], 'status': 'OK', 'request_id': '4fbcc7d316290686c866fc9f8d06f0a4', 'count': 2}
290
['RY', '2022-07-22', '2022-07-25']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1889948.0, 'vw': 96.2973, 'o': 96.53, 'c': 95.74, 'h': 97.12, 'l': 95.34, 't': 1658462400000, 'n': 10056}, {'v': 1965316.0, 'vw': 95.5226, 'o': 95.59, 'c': 95.9, 'h': 96.42, 'l': 95.305, 't': 1658721600000, 'n': 8243}], 'status': 'OK', 'request_id': '2fe85887be260dfa7a07bbc533c5625d', 'count': 2}
305
['BMO', '2022-10-28', '2022-10-31']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1938591.0, 'vw': 93.1573, 'o': 93.03, 'c': 93.9, 'h': 94.12, 'l': 92.85, 't': 1666929600000, 'n': 10672}, {'v': 1938775.0, 'vw': 92.0561, 'o': 92.01, 'c': 92.08, 'h': 93.04, 'l': 91.89, 't': 1667188800000, 'n': 9171}], 'status': 'OK', 'request_id': 'ee6b3028f3512f534ecdb5d50ba2e5e0', 'count': 2}
306
['BMO', '2022-07-29', '2022-08-01']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1799406.0, 'vw': 100.0935, 'o': 99.87, 'c': 100.72, 'h': 101.22, 'l': 99.74, 't': 1659067200000, 'n': 11085}, {'v': 1993972.0, 'vw': 98.5032, 'o': 99.38, 'c': 98.84, 'h': 99.81, 'l': 98.09, 't': 1659326400000, 'n': 7165}], 'status': 'OK', 'request_id': '114998e5fdf1ab25f8472d94b1920460', 'count': 2}
301
['RY', '2019-10-22', '2019-10-23']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 861525, 'vw': 82.2661, 'o': 82.34, 'c': 81.93, 'h': 82.58, 'l': 81.9, 't': 1571716800000, 'n': 9445}, {'v': 651308, 'vw': 81.1082, 'o': 80.99, 'c': 81.36, 'h': 81.36, 'l': 80.92, 't': 1571803200000, 'n': 7159}], 'status': 'OK', 'request_id': '82701cb09b2ada3e20be4d2fa25361c5', 'count': 2}
304
['BMO', '2023-01-26', '2023-01-27']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2150167.0, 'vw': 100.1999, 'o': 100.2, 'c': 101.49, 'h': 101.53, 'l': 99.84, 't': 1674709200000, 'n': 7633}, {'v': 1734397.0, 'vw': 99.9959, 'o': 100.43, 'c': 100.25, 'h': 100.52, 'l': 99.77, 't': 1674795600000, 'n': 6532}], 'status': 'OK', 'request_id': '7afae3e79607693840367a31a4aad7cf', 'count': 2}
302
['BMO', '2023-07-26', '2023-07-27']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1982295.0, 'vw': 93.1868, 'o': 93.09, 'c': 93.44, 'h': 93.97, 'l': 92.75, 't': 1690344000000, 'n': 10051}, {'v': 2907370.0, 'vw': 92.3511, 'o': 93.1, 'c': 91.86, 'h': 93.26, 'l': 91.65, 't': 1690430400000, 'n': 7826}], 'status': 'OK', 'request_id': '16128f308e761f8eb9d0eaefb5b20500', 'count': 2}
307
['BMO', '2022-04-28', '2022-04-29']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1181462.0, 'vw': 108.5165, 'o': 108.02, 'c': 109.19, 'h': 109.74, 'l': 107.38, 't': 1651118400000, 'n': 11468}, {'v': 1856963.0, 'vw': 107.6197, 'o': 108.43, 'c': 106.04, 'h': 109.19, 'l': 105.8, 't': 1651204800000, 'n': 11455}], 'status': 'OK', 'request_id': '4a2398d6f8a501242f96418adb384807', 'count': 2}
310
['BMO', '2021-07-30', '2021-08-02']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1416166.0, 'vw': 100.218, 'o': 100.79, 'c': 99.7, 'h': 101.59, 'l': 99.34, 't': 1627617600000, 'n': 15452}, {'v': 1686482.0, 'vw': 99.3543, 'o': 99.38, 'c': 98.12, 'h': 100.77, 'l': 97.791, 't': 1627876800000, 'n': 5919}], 'status': 'OK', 'request_id': '028ea0f6dd095901bc17e1bf6ed32349', 'count': 2}
286
['RY', '2023-07-24', '2023-07-25']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1382594.0, 'vw': 99.8307, 'o': 99.5, 'c': 100.28, 'h': 100.83, 'l': 99.18, 't': 1690171200000, 'n': 14046}, {'v': 2287409.0, 'vw': 98.4688, 'o': 99.3, 'c': 98.71, 'h': 99.435, 'l': 97.94, 't': 1690257600000, 'n': 13018}], 'status': 'OK', 'request_id': '4a239259484be2549b055b373c5b08c3', 'count': 2}
303
['BMO', '2023-04-26', '2023-04-27']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 705295, 'vw': 89.1136, 'o': 88.43, 'c': 89.09, 'h': 89.77, 'l': 88.34, 't': 1682481600000, 'n': 8321}, {'v': 1022269.0, 'vw': 89.4011, 'o': 88.26, 'c': 89.56, 'h': 89.6228, 'l': 88.06, 't': 1682568000000, 'n': 5781}], 'status': 'OK', 'request_id': 'a3b1eb5a9b1a63c878d5d4ce5b4b017f', 'count': 2}
262
['CBRL', '2022-07-13', '2022-07-14']
{'ticker': 'CBRL', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 488587, 'vw': 88.6273, 'o': 86.95, 'c': 89.27, 'h': 89.99, 'l': 86.2, 't': 1657684800000, 'n': 11794}, {'v': 407409, 'vw': 88.1151, 'o': 86.68, 'c': 88.38, 'h': 89.015, 'l': 86.68, 't': 1657771200000, 'n': 9709}], 'status': 'OK', 'request_id': '0b260933c926c0d5138ca1a7cb2a6c0e', 'count': 2}
292
['RY', '2022-01-24', '2022-01-25']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3267492.0, 'vw': 112.027, 'o': 112.89, 'c': 113.4, 'h': 113.6206, 'l': 110.79, 't': 1643000400000, 'n': 28532}, {'v': 2650853.0, 'vw': 111.4953, 'o': 111.7, 'c': 111.89, 'h': 112.91, 'l': 110.11, 't': 1643086800000, 'n': 20446}], 'status': 'OK', 'request_id': '1c0ab9ce03c5ed9b00ebea464827273e', 'count': 2}
273
['LOW', '2022-10-17', '2022-10-18']
{'ticker': 'LOW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3504756.0, 'vw': 193.7824, 'o': 192.25, 'c': 194.09, 'h': 195.215, 'l': 192.09, 't': 1665979200000, 'n': 53906}, {'v': 3804253.0, 'vw': 194.0509, 'o': 196.2, 'c': 193.2, 'h': 198.565, 'l': 192.56, 't': 1666065600000, 'n': 56206}], 'status': 'OK', 'request_id': 'c3153a0655e4433f6171c0aebae45b4c', 'count': 2}
287
['RY', '2023-04-21', '2023-04-24']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1364238.0, 'vw': 99.708, 'o': 99.6, 'c': 99.94, 'h': 100.02, 'l': 98.98, 't': 1682049600000, 'n': 13291}, {'v': 2675080.0, 'vw': 98.3998, 'o': 99.03, 'c': 98.67, 'h': 99.05, 'l': 98.2, 't': 1682308800000, 'n': 8106}], 'status': 'OK', 'request_id': 'c8f43663d45024cf3c2fb2b2a8a24f24', 'count': 2}
288
['RY', '2023-01-24', '2023-01-25']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2250418.0, 'vw': 100.4275, 'o': 101, 'c': 100.99, 'h': 101.23, 'l': 100.18, 't': 1674536400000, 'n': 9486}, {'v': 2781989.0, 'vw': 99.383, 'o': 99.94, 'c': 99.73, 'h': 100.11, 'l': 99.04, 't': 1674622800000, 'n': 8948}], 'status': 'OK', 'request_id': 'c140125155fd40d9e83984fae68cb704', 'count': 2}
268
['CBRL', '2020-01-15', '2020-01-16']
{'ticker': 'CBRL', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 471234, 'vw': 162.9426, 'o': 162.18, 'c': 162.63, 'h': 163.97, 'l': 161.64, 't': 1579064400000, 'n': 8381}, {'v': 422755, 'vw': 160.4093, 'o': 161.18, 'c': 159.38, 'h': 161.65, 'l': 159.27, 't': 1579150800000, 'n': 7825}], 'status': 'OK', 'request_id': '6bf866b39fa36d57701bd56087d9ebdc', 'count': 2}
309
['BMO', '2021-10-28', '2021-10-29']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 602029, 'vw': 111.9896, 'o': 111.33, 'c': 112.3, 'h': 112.34, 'l': 111.06, 't': 1635393600000, 'n': 8719}, {'v': 655094, 'vw': 109.4728, 'o': 110.76, 'c': 108.51, 'h': 111.491, 'l': 108.46, 't': 1635480000000, 'n': 9304}], 'status': 'OK', 'request_id': 'f65ba7c5dbf856312ca3deb4916902ad', 'count': 2}
312
['BMO', '2021-01-28', '2021-01-29']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 704542, 'vw': 76.6257, 'o': 76.16, 'c': 76.69, 'h': 77.12, 'l': 75.69, 't': 1611810000000, 'n': 7931}, {'v': 842033, 'vw': 74.6534, 'o': 75.7, 'c': 74.31, 'h': 76.16, 'l': 74.05, 't': 1611896400000, 'n': 6989}], 'status': 'OK', 'request_id': '3c0e7d552966ccd3d51d1e35caffd652', 'count': 2}
297
['RY', '2020-10-22', '2020-10-23']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1420579.0, 'vw': 74.0694, 'o': 73.5, 'c': 74.1, 'h': 74.31, 'l': 73.43, 't': 1603339200000, 'n': 8456}, {'v': 2481519.0, 'vw': 73.6608, 'o': 73.78, 'c': 73.3, 'h': 73.88, 'l': 73.13, 't': 1603425600000, 'n': 11263}], 'status': 'OK', 'request_id': '0851ab4923c58fcf24ebb9d3c6d2bdf8', 'count': 2}
314
['BMO', '2020-07-31', '2020-08-03']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1701670.0, 'vw': 55.6272, 'o': 55.81, 'c': 55.52, 'h': 55.92, 'l': 55.075, 't': 1596168000000, 'n': 8466}, {'v': 266189, 'vw': 54.9023, 'o': 55, 'c': 54.84, 'h': 55.1167, 'l': 54.55, 't': 1596427200000, 'n': 3016}], 'status': 'OK', 'request_id': 'f9f7017a60b7dded39d76f4a2743f8d2', 'count': 2}
315
['BMO', '2020-04-29', '2020-04-30']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 921571, 'vw': 53.18, 'o': 52.37, 'c': 53.76, 'h': 53.91, 'l': 52.2011, 't': 1588132800000, 'n': 9796}, {'v': 1057823.0, 'vw': 51.4238, 'o': 52.36, 'c': 50.9, 'h': 52.42, 'l': 50.87, 't': 1588219200000, 'n': 11438}], 'status': 'OK', 'request_id': 'b51cc94ad7381e09cc5f2429d24850df', 'count': 2}
308
['BMO', '2022-01-28', '2022-01-31']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1589104.0, 'vw': 112.5073, 'o': 113.37, 'c': 113.06, 'h': 113.37, 'l': 111.71, 't': 1643346000000, 'n': 10980}, {'v': 2471264.0, 'vw': 112.2054, 'o': 111.6, 'c': 113.18, 'h': 113.62, 'l': 111.18, 't': 1643605200000, 'n': 10773}], 'status': 'OK', 'request_id': 'f3322ba6f32e36c9ecafcab062149857', 'count': 2}
311
['BMO', '2021-04-29', '2021-04-30']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 877785, 'vw': 95.5522, 'o': 95.62, 'c': 95.58, 'h': 95.99, 'l': 95.24, 't': 1619668800000, 'n': 9322}, {'v': 1036785.0, 'vw': 94.3492, 'o': 94.38, 'c': 94.34, 'h': 94.77, 'l': 93.93, 't': 1619755200000, 'n': 10253}], 'status': 'OK', 'request_id': '56811a36cc4f087a2eb91fa2331ea9a0', 'count': 2}
317
['BMO', '2019-10-30', '2019-10-31']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2486968.0, 'vw': 74.8164, 'o': 75, 'c': 75.07, 'h': 75.14, 'l': 74.44, 't': 1572408000000, 'n': 7761}, {'v': 447995, 'vw': 74.0837, 'o': 74.19, 'c': 73.99, 'h': 74.6181, 'l': 73.73, 't': 1572494400000, 'n': 5706}], 'status': 'OK', 'request_id': 'f8e2c6612fe2474c74ccfff870803a14', 'count': 2}
313
['BMO', '2020-10-29', '2020-10-30']
{'ticker': 'BMO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 732119, 'vw': 60.4665, 'o': 59.83, 'c': 60.91, 'h': 61.11, 'l': 59.2, 't': 1603944000000, 'n': 7902}, {'v': 717307, 'vw': 59.4792, 'o': 60.04, 'c': 59.47, 'h': 60.12, 'l': 59.02, 't': 1604030400000, 'n': 7860}], 'status': 'OK', 'request_id': '8a802cddff1829ffccc279a21b34498e', 'count': 2}
316
['BMO', '2020-01-30', '2020-01-31']

23
['FRT', '2021-09-20', '2021-09-21']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 690089, 'vw': 117.7318, 'o': 117.24, 'c': 117.93, 'h': 118.7, 'l': 116.12, 't': 1632110400000, 'n': 9427}, {'v': 271150, 'vw': 117.4106, 'o': 118.14, 'c': 116.76, 'h': 118.45, 'l': 116.71, 't': 1632196800000, 'n': 7105}], 'status': 'OK', 'request_id': '75cc51ea023934999390d1bb903f255c', 'count': 2}
46
['PKG', '2019-12-18', '2019-12-19']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 535407, 'vw': 111.7624, 'o': 112.14, 'c': 111.78, 'h': 112.26, 'l': 111.3, 't': 1576645200000, 'n': 6368}, {'v': 658699, 'vw': 111.5704, 'o': 111.81, 'c': 111.67, 'h': 112.63, 'l': 111.14, 't': 1576731600000, 'n': 9759}], 'status': 'OK', 'request_id': '7707e91537a003564372d888ec590b71', 'count': 2}
177
['DE', '2019-09-26', '2019-09-27']
{'ticker': 'DE', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1834944.0, 'vw': 165.9095, 'o': 165.17, 'c': 166.41, 'h': 166.92, 'l': 164.75, 't': 1569470400000, 'n': 19801}, {'v': 1605650.0, 'vw': 166.1163, 'o': 166.5, 'c': 166.26, 'h': 167.31, 'l': 165, 't': 1569556800000, 'n': 19068}], 'status': 'OK', 'request_id': 'f93bd5d5136b487168346d2890d22bc8', 'count': 2}
105
['AVB', '2021-09-30', '2021-10-01']
{'ticker': 'AVB', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 583396, 'vw': 222.6473, 'o': 225.18, 'c': 221.64, 'h': 226.47, 'l': 221.51, 't': 1632974400000, 'n': 11061}, {'v': 338614, 'vw': 222.2077, 'o': 221.85, 'c': 222.76, 'h': 224.08, 'l': 218.77, 't': 1633060800000, 'n': 9559}], 'status': 'OK', 'request_id': 'a37a7d47b3289608f94190146543cf6f', 'count': 2}
234
['MAA', '2021-07-13', '2021-07-14']
{'ticker': 'MAA', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 400851, 'vw': 181.122, 'o': 182.33, 'c': 180.65, 'h': 182.76, 'l': 179.76, 't': 1626148800000, 'n': 8092}, {'v': 366981, 'vw': 181.9821, 'o': 179.63, 'c': 182.41, 'h': 182.51, 'l': 179.63, 't': 1626235200000, 'n': 6466}], 'status': 'OK', 'request_id': '7006dc13105aeaa78a77e85f8c88bbd9', 'count': 2}
90
['WPC', '2021-06-28', '2021-06-29']
{'ticker': 'WPC', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1182764.0, 'vw': 77.1228, 'o': 77.73, 'c': 77.15, 'h': 77.8373, 'l': 76.59, 't': 1624852800000, 'n': 11093}, {'v': 1243962.0, 'vw': 75.7346, 'o': 75.68, 'c': 75.33, 'h': 76.6089, 'l': 75.21, 't': 1624939200000, 'n': 12438}], 'status': 'OK', 'request_id': '19e8dc3bbf6e15abf92d4939716afd9b', 'count': 2}
85
['WPC', '2022-09-28', '2022-09-29']
{'ticker': 'WPC', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1647576.0, 'vw': 73.0187, 'o': 72.63, 'c': 72.99, 'h': 73.635, 'l': 71.86, 't': 1664337600000, 'n': 22502}, {'v': 2013621.0, 'vw': 68.6348, 'o': 71.35, 'c': 68.77, 'h': 71.76, 'l': 67.765, 't': 1664424000000, 'n': 32870}], 'status': 'OK', 'request_id': 'd2fd78e3b9443e251fbdb560feeb5e50', 'count': 2}
38
['PKG', '2021-12-16', '2021-12-17']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1001879.0, 'vw': 134.1656, 'o': 132.63, 'c': 134.5, 'h': 135.1, 'l': 132.31, 't': 1639630800000, 'n': 12147}, {'v': 1976800.0, 'vw': 131.1769, 'o': 133.62, 'c': 130.03, 'h': 133.75, 'l': 129.57, 't': 1639717200000, 'n': 16487}], 'status': 'OK', 'request_id': 'a33a2ce45b51f23e96a087b3731351f6', 'count': 2}
296
['RY', '2021-01-22', '2021-01-25']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 3054660.0, 'vw': 84.3686, 'o': 84.62, 'c': 84.3, 'h': 84.89, 'l': 84.12, 't': 1611291600000, 'n': 9093}, {'v': 2386326.0, 'vw': 83.0368, 'o': 83.55, 'c': 83.4, 'h': 83.88, 'l': 82.66, 't': 1611550800000, 'n': 8843}], 'status': 'OK', 'request_id': '42d33ecda97a3111fc04bc1a4de9d62a', 'count': 2}
42
['PKG', '2020-12-17', '2020-12-18']
{'ticker': 'PKG', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 504249, 'vw': 135.3546, 'o': 136, 'c': 135.65, 'h': 136.18, 'l': 134.21, 't': 1608181200000, 'n': 10589}, {'v': 1232527.0, 'vw': 134.4771, 'o': 134.73, 'c': 134.86, 'h': 135.11, 'l': 132.325, 't': 1608267600000, 'n': 10549}], 'status': 'OK', 'request_id': '986de1830e63bb075bfc0b97783a7886', 'count': 2}
49
['LOGI', '2020-09-17', '2020-09-18']
{'ticker': 'LOGI', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 917180, 'vw': 70.6443, 'o': 70.54, 'c': 70.47, 'h': 71.39, 'l': 69.81, 't': 1600315200000, 'n': 8601}, {'v': 936884, 'vw': 70.9237, 'o': 72.21, 'c': 70.58, 'h': 72.21, 'l': 69.705, 't': 1600401600000, 'n': 9827}], 'status': 'OK', 'request_id': 'c40bd4dae4cecb58f42234cee3f5da8c', 'count': 2}
203
['BNS', '2021-04-02', '2021-04-05']
{'ticker': 'BNS', 'queryCount': 1, 'resultsCount': 1, 'adjusted': True, 'results': [{'v': 4051905.0, 'vw': 62.4392, 'o': 62.43, 'c': 62.56, 'h': 62.79, 'l': 62.22, 't': 1617595200000, 'n': 12122}], 'status': 'OK', 'request_id': '9bbea707f423236cf136873932f7d3a1', 'count': 1}
197
['BNS', '2022-09-30', '2022-10-03']
{'ticker': 'BNS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4562244.0, 'vw': 48.1, 'o': 48.41, 'c': 47.57, 'h': 48.665, 'l': 47.525, 't': 1664510400000, 'n': 21394}, {'v': 3059343.0, 'vw': 47.8853, 'o': 47.49, 'c': 48.08, 'h': 48.34, 'l': 47.35, 't': 1664769600000, 'n': 21100}], 'status': 'OK', 'request_id': '365ab39b5b0d9efa6d799da17be3571d', 'count': 2}
218
['GD', '2021-06-30', '2021-07-01']
{'ticker': 'GD', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1115259.0, 'vw': 188.0207, 'o': 186.55, 'c': 188.26, 'h': 188.59, 'l': 186.51, 't': 1625025600000, 'n': 17356}, {'v': 907595, 'vw': 188.2233, 'o': 187.82, 'c': 188.05, 'h': 189.09, 'l': 187.28, 't': 1625112000000, 'n': 18384}], 'status': 'OK', 'request_id': 'cc529b8865281ae6e4215bb498178cee', 'count': 2}
51
['PM', '2023-03-21', '2023-03-22']
{'ticker': 'PM', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 4039610.0, 'vw': 95.8182, 'o': 96.95, 'c': 95.7, 'h': 97.37, 'l': 95.33, 't': 1679371200000, 'n': 47185}, {'v': 7748296.0, 'vw': 93.1602, 'o': 94.49, 'c': 92.37, 'h': 94.8, 'l': 92.23, 't': 1679457600000, 'n': 66756}], 'status': 'OK', 'request_id': 'c0daad8ad7d5441d0a77b049781ea2c1', 'count': 2}
151
['ITW', '2022-03-29', '2022-03-30']
{'ticker': 'ITW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 843516, 'vw': 218.0457, 'o': 216.64, 'c': 218.57, 'h': 220.3, 'l': 216.17, 't': 1648526400000, 'n': 19054}, {'v': 865913, 'vw': 214.9506, 'o': 216.56, 'c': 214.66, 'h': 217.8599, 'l': 213.59, 't': 1648612800000, 'n': 17065}], 'status': 'OK', 'request_id': 'a0419a96bd538aae1795416a709a0024', 'count': 2}
194
['BNS', '2023-07-03', '2023-07-05']
{'ticker': 'BNS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1230361.0, 'vw': 49.7537, 'o': 49.27, 'c': 49.69, 'h': 50.0459, 'l': 49.222, 't': 1688356800000, 'n': 6159}, {'v': 1793267.0, 'vw': 48.8448, 'o': 49.08, 'c': 48.79, 'h': 49.14, 'l': 48.67, 't': 1688529600000, 'n': 14127}], 'status': 'OK', 'request_id': '4ba3aee7cf2c76f1b81d339f4f2057bd', 'count': 2}
202
['BNS', '2021-07-01', '2021-07-02']
{'ticker': 'BNS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2690097.0, 'vw': 65.2898, 'o': 65.39, 'c': 65.58, 'h': 65.69, 'l': 65.1199, 't': 1625112000000, 'n': 7000}, {'v': 2912810.0, 'vw': 64.6376, 'o': 64.96, 'c': 65.01, 'h': 65.141, 'l': 64.46, 't': 1625198400000, 'n': 10409}], 'status': 'OK', 'request_id': 'dfe8670bab59d09391bb06bb25b57684', 'count': 2}
178
['APD', '2023-06-29', '2023-06-30']
{'ticker': 'APD', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 567836, 'vw': 293.6909, 'o': 289.94, 'c': 294.75, 'h': 295.29, 'l': 288.6, 't': 1688011200000, 'n': 15580}, {'v': 1031745.0, 'vw': 299.0259, 'o': 295.88, 'c': 299.53, 'h': 300.51, 'l': 295.17, 't': 1688097600000, 'n': 26858}], 'status': 'OK', 'request_id': 'a9c754e23c64ec62ca26703bbd03993a', 'count': 2}
26
['FRT', '2020-12-30', '2020-12-31']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 691634, 'vw': 86.1445, 'o': 85.61, 'c': 85.88, 'h': 87.75, 'l': 85.33, 't': 1609304400000, 'n': 10701}, {'v': 732625, 'vw': 84.5164, 'o': 84.65, 'c': 85.12, 'h': 85.24, 'l': 83.1, 't': 1609390800000, 'n': 10544}], 'status': 'OK', 'request_id': 'b95ac9b40aa9fe28b947e76d8b74accc', 'count': 2}
72
['ESS', '2021-12-30', '2021-12-31']
{'ticker': 'ESS', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 179772, 'vw': 352.6165, 'o': 352.03, 'c': 352.69, 'h': 354.31, 'l': 351.06, 't': 1640840400000, 'n': 6316}, {'v': 204508, 'vw': 353.0603, 'o': 351.48, 'c': 352.23, 'h': 355.07, 'l': 351.48, 't': 1640926800000, 'n': 4989}], 'status': 'OK', 'request_id': 'aa65a5e89ebe14042da748cabc279857', 'count': 2}

9
['AVGO', '2021-03-18', '2021-03-19']
{'ticker': 'AVGO', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2874329.0, 'vw': 471.6172, 'o': 474.56, 'c': 464.15, 'h': 483.35, 'l': 463.75, 't': 1616040000000, 'n': 58685}, {'v': 10860245.0, 'vw': 471.1027, 'o': 457.05, 'c': 474.46, 'h': 476.675, 'l': 454.1, 't': 1616126400000, 'n': 73422}], 'status': 'OK', 'request_id': '693ca5ff3f405b8a1cb58fb56a9f18d8', 'count': 2}
19
['FRT', '2022-09-20', '2022-09-21']
{'ticker': 'FRT', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 795195, 'vw': 96.8681, 'o': 99.06, 'c': 96.28, 'h': 99.595, 'l': 95.92, 't': 1663646400000, 'n': 17588}, {'v': 518256, 'vw': 94.7494, 'o': 95.85, 'c': 93.29, 'h': 96.9013, 'l': 93.22, 't': 1663732800000, 'n': 11478}], 'status': 'OK', 'request_id': '5c0b1ca7145aac6b36b01ffd7f86a2db', 'count': 2}
147
['ITW', '2023-03-29', '2023-03-30']
{'ticker': 'ITW', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1427678.0, 'vw': 238.2948, 'o': 236.54, 'c': 239.44, 'h': 239.47, 'l': 235.5, 't': 1680062400000, 'n': 26657}, {'v': 991061, 'vw': 240.2889, 'o': 239.21, 'c': 239.88, 'h': 242.17, 'l': 238.92, 't': 1680148800000, 'n': 26088}], 'status': 'OK', 'request_id': 'be6a59213ebac7866bbf6b9ecb1d478a', 'count': 2}
299
['RY', '2020-04-21', '2020-04-22']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 2477239.0, 'vw': 59.5153, 'o': 59.99, 'c': 59.12, 'h': 60.91, 'l': 59.07, 't': 1587441600000, 'n': 26010}, {'v': 1414938.0, 'vw': 58.5885, 'o': 59.44, 'c': 58.43, 'h': 59.58, 'l': 58.195, 't': 1587528000000, 'n': 17617}], 'status': 'OK', 'request_id': '87c94ad7ea7420d5c4bd918d3b2bb1d4', 'count': 2}
250
['ABBV', '2021-07-13', '2021-07-14']
{'ticker': 'ABBV', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 6628760.0, 'vw': 117.6396, 'o': 117.59, 'c': 117.91, 'h': 118.09, 'l': 116.69, 't': 1626148800000, 'n': 56740}, {'v': 6624833.0, 'vw': 117.0637, 'o': 116.87, 'c': 117.36, 'h': 117.55, 'l': 116.39, 't': 1626235200000, 'n': 59281}], 'status': 'OK', 'request_id': '01c3feb61fa73457033a949a5d37028a', 'count': 2}
140
['EGP', '2020-12-29', '2020-12-30']
{'ticker': 'EGP', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 114234, 'vw': 136.8278, 'o': 139.37, 'c': 136.44, 'h': 139.44, 'l': 136.12, 't': 1609218000000, 'n': 3706}, {'v': 135168, 'vw': 137.3379, 'o': 135.76, 'c': 137.53, 'h': 137.89, 'l': 135.76, 't': 1609304400000, 'n': 3097}], 'status': 'OK', 'request_id': '00c9cff5f8ca3dd0b4a7cdc426360d02', 'count': 2}
168
['DE', '2021-12-29', '2021-12-30']
{'ticker': 'DE', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 1417325.0, 'vw': 346.8496, 'o': 348.36, 'c': 345.71, 'h': 349.31, 'l': 345.5, 't': 1640754000000, 'n': 29730}, {'v': 1539028.0, 'vw': 343.6963, 'o': 345.81, 'c': 342.03, 'h': 348.05, 'l': 341.84, 't': 1640840400000, 'n': 32826}], 'status': 'OK', 'request_id': '38798c5609694b14bc7aa3622e08740b', 'count': 2}
294
['RY', '2021-07-22', '2021-07-23']
{'ticker': 'RY', 'queryCount': 2, 'resultsCount': 2, 'adjusted': True, 'results': [{'v': 871782, 'vw': 100.053, 'o': 100.52, 'c': 100.14, 'h': 100.73, 'l': 99.67, 't': 1626926400000, 'n': 9605}, {'v': 2014040.0, 'vw': 99.8439, 'o': 99.51, 'c': 99.97, 'h': 100.24, 'l': 99.51, 't': 1627012800000, 'n': 11778}], 'status': 'OK', 'request_id': '73a816c4f53cf409421a098fd12e9efb', 'count': 2}

In [19]:
to_drop

[4, 20, 206, 204, 276, 284, 280, 203]

In [47]:
div_yields

,ticker,prior_business_date,ex_dividend_date,cash_amount,dividend_type,frequency,declaration_date,record_date,pay_date,prior_biz_close,xdiv_close,delta
0,AVGO,2023-06-20,2023-06-21,4.60,CD,4,2023-06-01,2023-06-22,2023-06-30,143.85,138.86,-4.99
1,AVGO,2023-03-20,2023-03-21,4.60,CD,4,2023-03-03,2023-03-22,2023-03-31,132.88,130.58,-2.30
2,AVGO,2022-12-16,2022-12-19,4.60,CD,4,2022-12-08,2022-12-20,2022-12-30,84.17,82.19,-1.98
3,AVGO,2022-09-20,2022-09-21,4.10,CD,4,2022-09-01,2022-09-22,2022-09-30,77.01,75.50,-1.51
4,AVGO,2022-06-20,2022-06-21,4.10,CD,4,2022-05-26,2022-06-22,2022-06-30,94.25,92.37,-1.88
...,...,...,...,...,...,...,...,...,...,...,...,...
313,BMO,2020-10-29,2020-10-30,1.06,CD,4,2020-08-25,2020-11-02,2020-11-26,59.12,58.43,-0.69
314,BMO,2020-07-31,2020-08-03,1.06,CD,4,2020-05-27,2020-08-04,2020-08-26,117.91,117.36,-0.55
315,BMO,2020-04-29,2020-04-30,1.06,CD,4,2020-02-25,2020-05-01,2020-05-26,136.44,137.53,1.09
316,BMO,2020-01-30,2020-01-31,1.06,CD,4,2019-12-03,2020-02-03,2020-02-26,345.71,342.03,-3.68
317,BMO,2019-10-30,2019-10-31,1.03,CD,4,2019-08-27,2019-11-01,2019-11-26,100.14,99.97,-0.17

In [21]:
len(div_yields)

318

In [22]:
# for i in to_drop:
#     div_yields.drop(div_yields.iloc[i])

In [23]:
len(xdiv_close)

318

In [24]:
len(prior_biz_close)

318

In [25]:
len(prior_biz_close) == len(xdiv_close)

True

In [26]:
len(to_drop)

8

In [27]:
# res = [*set(to_drop)] #remove duplicates in to_drop
# len(res)

In [28]:
# len(div_yields) - len(res)

In [29]:
# div_yields['prior_biz_close']
div_yields

,ticker,prior_business_date,ex_dividend_date,cash_amount,dividend_type,frequency,declaration_date,record_date,pay_date
0,AVGO,2023-06-20,2023-06-21,4.60,CD,4,2023-06-01,2023-06-22,2023-06-30
1,AVGO,2023-03-20,2023-03-21,4.60,CD,4,2023-03-03,2023-03-22,2023-03-31
2,AVGO,2022-12-16,2022-12-19,4.60,CD,4,2022-12-08,2022-12-20,2022-12-30
3,AVGO,2022-09-20,2022-09-21,4.10,CD,4,2022-09-01,2022-09-22,2022-09-30
4,AVGO,2022-06-20,2022-06-21,4.10,CD,4,2022-05-26,2022-06-22,2022-06-30
...,...,...,...,...,...,...,...,...,...
313,BMO,2020-10-29,2020-10-30,1.06,CD,4,2020-08-25,2020-11-02,2020-11-26
314,BMO,2020-07-31,2020-08-03,1.06,CD,4,2020-05-27,2020-08-04,2020-08-26
315,BMO,2020-04-29,2020-04-30,1.06,CD,4,2020-02-25,2020-05-01,2020-05-26
316,BMO,2020-01-30,2020-01-31,1.06,CD,4,2019-12-03,2020-02-03,2020-02-26
317,BMO,2019-10-30,2019-10-31,1.03,CD,4,2019-08-27,2019-11-01,2019-11-26

In [30]:
len(xdiv_close)

318

In [31]:
# div_yields = div_yields.drop(div_yields.index[res]) #drop missing data from the dataframe where bars aren't available
# div_yields = div_yields.drop(index=res)
# '''
#     /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py:5055: 
#     FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; 
#     use `arr[tuple(seq)]` instead of `arr[seq]`. 
#     In the future this will be interpreted as an array index, `arr[np.array(seq)]`, 
#     which will result either in an error or a different result. result = getitem(key)
# '''

## Step 7: Add the prior business close and ex-dividend close data to the dataframe

In [32]:
div_yields['prior_biz_close'] = prior_biz_close
div_yields['xdiv_close'] = xdiv_close
# len(div_yields) #50
# len(xdiv_close) #41
# len(prior_biz_close) #41

In [33]:
#remove all instances of rows where column value is 0.00
div_yields = div_yields[div_yields.prior_biz_close != 0]
# div_yields

## Step 8: Subtract the ex-dividend date from the prior business close to find the delta

In [34]:
div_yields['delta'] =  div_yields['xdiv_close'] - div_yields['prior_biz_close']
# div_yields

/var/folders/wk/zgdj52nx75gcms8jvb82chd00000gp/T/ipykernel_6953/887779326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  div_yields['delta'] =  div_yields['xdiv_close'] - div_yields['prior_biz_close']

In [35]:
#https://www.kite.com/blog/python/pandas-groupby-count-value-count/
import numpy as np
v = div_yields.groupby('ticker')

v['delta'].agg(np.mean)
b = pd.DataFrame(v['delta'].agg(np.mean))
b

           delta
ticker
ABBV   -0.887143
APD     0.165000
ARE    -0.293125
AVB    -1.057500
AVGO   -4.372000
BMO    -0.100000
BNS    -2.463750
CBRL   -1.755833
DE      0.311333
EGP    -1.190000
ESS    -2.086250
FRT    -1.814375
GD     -0.372667
ITW    -0.428125
LOGI   -3.706667
LOW    -0.680000
MAA    -0.200000
PKG    -0.956429
PM     -0.473750
RY     -0.778667
WPC    -1.901250

In [36]:
g = div_yields.groupby('ticker')['delta']
l = pd.DataFrame(g.agg(
    pos_count=lambda s: s.gt(0).sum(),
    neg_count=lambda s: s.lt(0).sum(),
    net_count=lambda s: s.gt(0).sum() + s.lt(0).sum()).astype(int))
    # open_down=lambda s: pos_count/net_count
t = pd.concat([b,l], axis=1)
t['decrease_liklihood_%'] = (t['neg_count']/t['net_count'])*100 
t['increase_liklihood_%'] = (t['pos_count']/t['net_count'])*100
t.reset_index()

,ticker,delta,pos_count,neg_count,net_count,decrease_liklihood_%,increase_liklihood_%
0,ABBV,-0.887143,5,9,14,64.285714,35.714286
1,APD,0.165000,7,9,16,56.250000,43.750000
2,ARE,-0.293125,6,10,16,62.500000,37.500000
3,AVB,-1.057500,5,11,16,68.750000,31.250000
4,AVGO,-4.372000,1,14,15,93.333333,6.666667
5,BMO,-0.100000,4,12,16,75.000000,25.000000
6,BNS,-2.463750,4,12,16,75.000000,25.000000
7,CBRL,-1.755833,1,11,12,91.666667,8.333333
8,DE,0.311333,7,8,15,53.333333,46.666667
9,EGP,-1.190000,5,11,16,68.750000,31.250000
10,ESS,-2.086250,2,14,16,87.500000,12.500000
11,FRT,-1.814375,5,11,16,68.750000,31.250000
12,GD,-0.372667,4,11,15,73.333333,26.666667
13,ITW,-0.428125,5,11,16,68.750000,31.250000
14,LOGI,-3.706667,0,3,3,100.000000,0.000000
15,LOW,-0.680000,5,11,16,68.750000,31.250000
16,MAA,-0.200000,5,10,15,66.666667,33.333333
17,PKG,-0.956429,5,9,14,64.285714,35.714286
18,PM,-0.473750,6,10,16,62.500000,37.500000
19,RY,-0.778667,5,10,15,66.666667,33.333333
20,WPC,-1.901250,5,11,16,68.750000,31.250000

In [37]:
# https://www.geeksforgeeks.org/how-to-sum-negative-and-positive-values-using-groupby-in-pandas/
def pos(col): 
  return col[col > 0].mean()
  
def neg(col): 
  return col[col < 0].mean()

# print(['Y'].agg([('negative_values', neg),
#                   ('positive_values', pos)
#                   ]))

w = div_yields.groupby(div_yields['ticker'])

s = pd.DataFrame(w['delta'].agg([('average_increase', neg),
                  ('average_decrease', pos)
                  ]))
s = s.fillna(0)
s = abs(s)
s['average_decrease'] = -s['average_decrease']
s = pd.concat([t,s], axis=1)
s = s.round({'delta': 2, 'average_increase': 2, 'average_decrease': 2})
s = s[['pos_count', 'neg_count', 'net_count', 'decrease_liklihood_%', 'average_decrease', 'increase_liklihood_%','average_increase','delta']]
s

,pos_count,neg_count,net_count,decrease_liklihood_%,average_decrease,increase_liklihood_%,average_increase,delta
ticker,,,,,,,,
ABBV,5,9,14,64.285714,-0.71,35.714286,1.78,-0.89
APD,7,9,16,56.250000,-2.13,43.750000,1.36,0.16
ARE,6,10,16,62.500000,-2.24,37.500000,1.81,-0.29
AVB,5,11,16,68.750000,-0.78,31.250000,1.89,-1.06
AVGO,1,14,15,93.333333,-1.21,6.666667,4.77,-4.37
BMO,4,12,16,75.000000,-4.15,25.000000,1.52,-0.10
BNS,4,12,16,75.000000,-0.97,25.000000,3.61,-2.46
CBRL,1,11,12,91.666667,-0.47,8.333333,1.96,-1.76
DE,7,8,15,53.333333,-2.37,46.666667,1.49,0.31
EGP,5,11,16,68.750000,-1.72,31.250000,2.51,-1.19
ESS,2,14,16,87.500000,-1.31,12.500000,2.57,-2.09
FRT,5,11,16,68.750000,-1.50,31.250000,3.32,-1.81
GD,4,11,15,73.333333,-3.12,26.666667,1.64,-0.37
ITW,5,11,16,68.750000,-3.18,31.250000,2.07,-0.43
LOGI,0,3,3,100.000000,-0.00,0.000000,3.71,-3.71
LOW,5,11,16,68.750000,-1.30,31.250000,1.58,-0.68
MAA,5,10,15,66.666667,-2.24,33.333333,1.42,-0.20
PKG,5,9,14,64.285714,-2.90,35.714286,3.10,-0.96
PM,6,10,16,62.500000,-1.64,37.500000,1.74,-0.47
RY,5,10,15,66.666667,-0.80,33.333333,1.57,-0.78
WPC,5,11,16,68.750000,-0.85,31.250000,3.15,-1.90

In [38]:
high_volume

,ticker,cash_amount,dividend_type,declaration_date,ex_dividend_date,record_date,pay_date,last_close,last_volume
0,AVGO,4.60,CD,2023-08-31,2023-09-20,2023-09-21,2023-09-29,851.68,5018958.0
1,TKO,3.86,SC,2023-09-13,2023-09-21,2023-09-22,2023-09-29,100.11,2453515.0
20,FRT,1.09,CD,2023-08-03,2023-09-21,2023-09-22,2023-10-16,98.82,674064.0
17,PKG,1.25,CD,2023-09-13,2023-09-22,2023-09-25,2023-10-13,149.75,1049844.0
22,LOGI,1.06,CD,2023-07-14,2023-09-25,2023-09-26,2023-09-27,71.53,1013144.0
14,PM,1.30,CD,2023-09-13,2023-09-26,2023-09-27,2023-10-12,95.79,6932697.0
2,ESS,2.31,CD,2023-09-07,2023-09-28,2023-09-29,2023-10-13,225.22,596433.0
21,WPC,1.07,CD,2023-09-14,2023-09-28,2023-09-29,2023-10-16,64.08,1735178.0
6,AVB,1.65,CD,2023-09-14,2023-09-28,2023-09-29,2023-10-16,183.89,1391249.0
18,ARE,1.24,CD,2023-09-04,2023-09-28,2023-09-29,2023-10-13,113.73,1892239.0
16,EGP,1.27,CD,2023-08-25,2023-09-28,2023-09-29,2023-10-13,178.82,560439.0
10,ITW,1.40,CD,2023-08-04,2023-09-28,2023-09-29,2023-10-12,238.31,1541503.0
12,DE,1.35,CD,2023-08-30,2023-09-28,2023-09-29,2023-11-08,412.11,1986245.0
4,APD,1.75,CD,2023-07-21,2023-09-29,2023-10-02,2023-11-13,302.11,1354643.0
23,BNS,1.06,CD,2023-08-29,2023-10-02,2023-10-03,2023-10-27,48.44,1412380.0
13,GD,1.32,CD,2023-08-01,2023-10-05,2023-10-06,2023-11-10,224.05,1829031.0
9,MAA,1.40,CD,2023-09-12,2023-10-12,2023-10-13,2023-10-31,138.00,970359.0
7,ABBV,1.48,CD,2023-09-08,2023-10-12,2023-10-13,2023-11-15,152.12,8868282.0
15,CBRL,1.30,CD,2023-09-13,2023-10-19,2023-10-20,2023-11-07,69.43,1082434.0
19,LOW,1.10,CD,2023-08-18,2023-10-24,2023-10-25,2023-11-08,220.02,9188534.0
11,RY,1.35,CD,2023-08-24,2023-10-25,2023-10-26,2023-11-24,91.51,1317577.0
8,BMO,1.47,CD,2023-08-29,2023-10-27,2023-10-30,2023-11-28,88.56,1149801.0

In [39]:
high_volume = high_volume[['ticker','last_close','last_volume', 'cash_amount', 'dividend_type','ex_dividend_date','record_date','pay_date']]
o = pd.merge(high_volume, s, how="outer", on=["ticker"])
o = o.fillna('-')
o['div%'] = (o['cash_amount']/o['last_close'])*100
o = o.round({'last_close': 2, 'cash_amount': 2, 'div%': 2})
o = o.rename(columns={
    'dividend_type': 'type', 
    'pos_count': '#+', 
    'neg_count': '#-', 
    'net_count': 'total', 
    'decrease_liklihood_%': '↓µ%', 
    'average_decrease': '↓µ$',
    'increase_liklihood_%': '↑µ%',
    'average_increase': '↑µ$',
    'delta': '∆'
})
o.sort_values(['ex_dividend_date'], inplace=True)
o = o.round({'↓µ%': 0, '↑µ%': 0})
o = o[['ticker', 'last_close', 'last_volume', 'cash_amount', 'div%', 'type', 'ex_dividend_date', 'record_date', 'pay_date', '#+', '#-', 'total', '↓µ%', '↓µ$', '↑µ%', '↑µ$', '∆']]
o
# o[o['volume'].between(0, 500000)] #filter by volume > 500,000

,ticker,last_close,last_volume,cash_amount,div%,type,ex_dividend_date,record_date,pay_date,#+,#-,total,↓µ%,↓µ$,↑µ%,↑µ$,∆
0,AVGO,851.68,5018958.0,4.60,0.54,CD,2023-09-20,2023-09-21,2023-09-29,1.0,14.0,15.0,93.333333,-1.21,6.666667,4.77,-4.37
1,TKO,100.11,2453515.0,3.86,3.86,SC,2023-09-21,2023-09-22,2023-09-29,-,-,-,-,-,-,-,-
2,FRT,98.82,674064.0,1.09,1.10,CD,2023-09-21,2023-09-22,2023-10-16,5.0,11.0,16.0,68.75,-1.5,31.25,3.32,-1.81
3,PKG,149.75,1049844.0,1.25,0.83,CD,2023-09-22,2023-09-25,2023-10-13,5.0,9.0,14.0,64.285714,-2.9,35.714286,3.1,-0.96
4,LOGI,71.53,1013144.0,1.06,1.48,CD,2023-09-25,2023-09-26,2023-09-27,0.0,3.0,3.0,100.0,-0.0,0.0,3.71,-3.71
5,PM,95.79,6932697.0,1.30,1.36,CD,2023-09-26,2023-09-27,2023-10-12,6.0,10.0,16.0,62.5,-1.64,37.5,1.74,-0.47
12,DE,412.11,1986245.0,1.35,0.33,CD,2023-09-28,2023-09-29,2023-11-08,7.0,8.0,15.0,53.333333,-2.37,46.666667,1.49,0.31
11,ITW,238.31,1541503.0,1.40,0.59,CD,2023-09-28,2023-09-29,2023-10-12,5.0,11.0,16.0,68.75,-3.18,31.25,2.07,-0.43
9,ARE,113.73,1892239.0,1.24,1.09,CD,2023-09-28,2023-09-29,2023-10-13,6.0,10.0,16.0,62.5,-2.24,37.5,1.81,-0.29
10,EGP,178.82,560439.0,1.27,0.71,CD,2023-09-28,2023-09-29,2023-10-13,5.0,11.0,16.0,68.75,-1.72,31.25,2.51,-1.19
7,WPC,64.08,1735178.0,1.07,1.67,CD,2023-09-28,2023-09-29,2023-10-16,5.0,11.0,16.0,68.75,-0.85,31.25,3.15,-1.9
6,ESS,225.22,596433.0,2.31,1.03,CD,2023-09-28,2023-09-29,2023-10-13,2.0,14.0,16.0,87.5,-1.31,12.5,2.57,-2.09
8,AVB,183.89,1391249.0,1.65,0.90,CD,2023-09-28,2023-09-29,2023-10-16,5.0,11.0,16.0,68.75,-0.78,31.25,1.89,-1.06
13,APD,302.11,1354643.0,1.75,0.58,CD,2023-09-29,2023-10-02,2023-11-13,7.0,9.0,16.0,56.25,-2.13,43.75,1.36,0.16
14,BNS,48.44,1412380.0,1.06,2.19,CD,2023-10-02,2023-10-03,2023-10-27,4.0,12.0,16.0,75.0,-0.97,25.0,3.61,-2.46
15,GD,224.05,1829031.0,1.32,0.59,CD,2023-10-05,2023-10-06,2023-11-10,4.0,11.0,15.0,73.333333,-3.12,26.666667,1.64,-0.37
16,MAA,138.00,970359.0,1.40,1.01,CD,2023-10-12,2023-10-13,2023-10-31,5.0,10.0,15.0,66.666667,-2.24,33.333333,1.42,-0.2
17,ABBV,152.12,8868282.0,1.48,0.97,CD,2023-10-12,2023-10-13,2023-11-15,5.0,9.0,14.0,64.285714,-0.71,35.714286,1.78,-0.89
18,CBRL,69.43,1082434.0,1.30,1.87,CD,2023-10-19,2023-10-20,2023-11-07,1.0,11.0,12.0,91.666667,-0.47,8.333333,1.96,-1.76
19,LOW,220.02,9188534.0,1.10,0.50,CD,2023-10-24,2023-10-25,2023-11-08,5.0,11.0,16.0,68.75,-1.3,31.25,1.58,-0.68
20,RY,91.51,1317577.0,1.35,1.48,CD,2023-10-25,2023-10-26,2023-11-24,5.0,10.0,15.0,66.666667,-0.8,33.333333,1.57,-0.78
21,BMO,88.56,1149801.0,1.47,1.66,CD,2023-10-27,2023-10-30,2023-11-28,4.0,12.0,16.0,75.0,-4.15,25.0,1.52,-0.1

In [40]:
# df2 = div_yields.ticker.unique()
# df2[0]

In [41]:
# import matplotlib.pyplot as plt
# # import seaborn as sns
# # for i in df2
# ser = pd.Series(div_yields.loc[div_yields.ticker==df2[0]]['delta'])
# # plt.plot(label=df2[0])
# plt.legend(loc='upper left', title=df2[0])
# ser.plot.kde();

In [42]:
# # for i in div_yields.index:
# #     print(div_yields['ticker'][i])
    
# import matplotlib.pyplot as plt
# for i in div_yields.index:
#     ser = div_yields['delta'][i]
#     plt.plot(label=div_yields['ticker'][i])
# #     plt.legend(loc='upper left', div_yields['ticker'][i])
#     ser.plot.kde();

In [43]:
# import seaborn as sns
# sns.set()

# # o.plot(x="ticker", y=["↓µ%"],
# #         kind="line", figsize=(10, 10), grid=True)
# data = o[['ticker','↓µ%']].copy()
# data = pd.DataFrame(data, columns=['x', 'y'])

# sns.distplot(data['y'])
# # for col in 'xy':
# #     sns.kdeplot(data[col], shade=True)

In [44]:
# Converting to wide dataframe
# https://stackoverflow.com/questions/41825939/plot-pandas-dataframe-two-columns
# https://www.geeksforgeeks.org/multiple-density-plots-with-pandas-in-python/
# https://stackoverflow.com/questions/40101519/plotting-event-density-in-python-with-ggplot-and-pandas
# https://realpython.com/ggplot-python/
# https://stackoverflow.com/questions/34682828/extracting-specific-selected-columns-to-new-dataframe-as-a-copy

In [45]:
# ser = pd.Series(div_yields.loc[div_yields.ticker==df2[0]]['delta'])
# plt.plot(label=df2[0])
# https://stackoverflow.com/questions/41825939/plot-pandas-dataframe-two-columns
# high_volume[['↓µ%','↓µ$']].plot()

# fig, ax1 = plt.subplots()

# x = o['ticker']
# y1 = o['↓µ%']
# y2 = o['↓µ$']

# ax2 = ax1.twinx()

# ax1.plot(x, y1, 'g-')
# ax2.plot(x, y2, 'b-')
# plt.show()

In [46]:
ser = pd.Series(div_yields.loc[div_yields.ticker=='AMGN']['delta'])
plt.legend(loc='upper left', title=df2[1])
ser.plot.kde();

NameError: name 'plt' is not defined

In [ ]:
# ser.plot.hist(alpha=0.5);

In [ ]:
# # https://pandas.pydata.org/docs/user_guide/visualization.html

# ser = pd.Series()
# ser.plot.kde();

In [ ]:
# div_yields.groupby([div_yields.ticker, div_yields.delta]).plot.kde();